mattermost/mattermost-plugin-calls

Makefile

Credit to @agarciamontoro for the implementation that checks `MM_SERVICESETTINGS_ENABLEDEVELOPER` and just builds a single platform for the current operating system and architecture.
N/A

If on a developer environment, build one binary

---

server/websocket.go

This didn't get included originally cause I thought we could figure it out by looking at the first user who joined a call but a little redundancy makes for easier queries on the analytics side so we are adding it here as well.

Add userID to call started telemetry event

---

webapp/src/index.tsx

I originally thought this bug was somehow due to the how community operates (pods rolling during upgrades) cause I wasn't able to reproduce but after a good amount of pure try and fail I was able to figure out it was switching channels/teams very quickly that caused it. This is because I failed to account of an async call which was delaying registering operations eventually leading to a leak.
The other issue (duplicate call icon next to channel name) is still a bit of a mystery since the component is only ever registered at plugin initialization so trying to force an unsubscribe although I don't believe it to be necessary. Will monitor for further occurrences.
https://mattermost.atlassian.net/browse/MM-42078

[MM-42078] Fix possible multiple component registrations

---

server/session.go
server/sfu.go

This was a rather odd bug that happened today for the first time (as far as I can recall). Some minutes into the call new users joining were not able to be heard from other participants even though they were unmuted and sending voice data.
Luckily I was able to reproduce this behaviour on a test cluster and examined the goroutine dump which revealed a goroutine stuck sending tracks to some users:
```
goroutine 15365 [chan send, 7 minutes]:
main.(*Plugin).initRTCConn.func5.1(0xc003544480)
github.com/mattermost/mattermost-plugin-calls/server/sfu.go:369 +0x69
main.(*Plugin).iterSessions(0xc000434180, {0xc00594cd80, 0x1a}, 0xc005257f00)
github.com/mattermost/mattermost-plugin-calls/server/utils.go:51 +0x14a
main.(*Plugin).initRTCConn.func5(0xc005a3ea20, 0xc0046e6798) …
```

[MM-42102] Fix tracks sending goroutine getting stuck due to missing signaling message

---

plugin.json
server/api.go
server/configuration.go
server/configuration_test.go
server/manifest.go
server/session.go
webapp/src/client.ts

We are adding a new `DefaultEnabled` config option that controls whether Calls should be enabled in all channels by default (opt-out model). 
https://mattermost.atlassian.net/browse/MM-42101

[MM-42101] Implement option to enable calls by default

---

webapp/src/components/call_widget/component.tsx

PR fixes the issue although I am also looking for some general feedback to see if we need to plan extra changes.
As things stand we have space for up to 17 characters in single team mode and 26 with the sidebar. If we don't set a max width very long names tend to go a bit over the right almost touching the expand icon which may feel a little compressed (see picture). 
Test string was `Some very very long channel name`.
/cc @itao 
https://mattermost.atlassian.net/browse/MM-42198

[MM-42198] Fix wrapping of long channel names

---

server/activate.go

PR fixes an issue with the UDP server connection not respecting the defined deadlines and hence potentially getting stuck indefinitely in case of an unreachable host.
After some testing and looking into the standard library I've figure out this was actually caused by the call on [`File.Fd()`](https://pkg.go.dev/os#File.Fd) we do here:
https://github.com/mattermost/mattermost-plugin-calls/blob/4ac8eb9ee52ed2d83a76a7ed8e6740c2ec54d34c/server/activate.go#L55-L64
As suggested in the official documentation we are now using [`File.SyscallConn()`](https://pkg.go.dev/os#File.SyscallConn) instead which seems to avoid this problem.
https://mattermost.atlassian.net/browse/MM-42347

[MM-42347] Fix UDP conn not respecting deadlines

---

e2e/tests/popout.spec.ts
webapp/package-lock.json
webapp/package.json
webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/index.ts
webapp/src/index.tsx
webapp/src/types/mattermost-webapp/index.d.ts

PR sets a more descriptive title to the pop-out window to be more easily identifiable.
Title format is `Call - $channel_display_name`. In case of DM, the username of the other participant is used instead.
/cc @aaronrothschild 
https://mattermost.atlassian.net/browse/MM-42385

[MM-42385] Set title to popout window

---

plugin.json

No more 3rd parties! Updating the default STUN server URL to our very own, Mattermost hosted one.
Huge thanks to @DSchalla for making this happen :raised_hands: 
https://mattermost.atlassian.net/browse/MM-42457

[MM-42457] Update default STUN server

---

webapp/src/client.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/component.tsx
webapp/src/index.tsx

Fixes https://github.com/mattermost/mattermost-server/issues/19710
We weren't properly de-initializing resources when the window got closed and screen sharing was initiated from it.
https://mattermost.atlassian.net/browse/MM-42315

[MM-42385] Fix closing popout while screensharing from it

---

server/websocket.go

Looks like the `UserID` is conflicting with another one named similarly which identifies the server (aka diagnostic ID) which prevented it from going through Snowflake. Changing to `ParticipantID` to make it pass.

Fix UserID not getting through Snowflake

---

server/api.go
server/channel_state.go

- Turns out this was caused by forgetting to send over the state for each user in the GET `/channels` route 😄 
- https://mattermost.atlassian.net/browse/MM-42433

[MM-42433] Fix: Calls mobile: microphone state gets reset when app switching

---

webapp/src/components/call_widget/component.scss
webapp/src/components/call_widget/component.tsx

PR implements the channel link in call widget. Upon clicking the channel is switched without causing a reload. It will also work if currently focusing a different product (on browser that is). I've tested on Desktop App as well and working as expected.
https://user-images.githubusercontent.com/1832946/157699676-3b5df2df-2d24-415a-b49c-02b44f82e8b5.mp4
https://mattermost.atlassian.net/browse/MM-42419

[MM-42419] Implement channel link in call widget

---

e2e/tests/popout.spec.ts
webapp/src/components/expanded_view/component.tsx

Small bug: we were also setting the parent window's title due to the component being loaded there as well. Added a check to avoid this from happening and updated the e2e test.

Fix setting pop-out window title

---

e2e/tests/start_call.spec.ts
webapp/src/client.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/icons/speaker_icon.tsx

PR implements a new menu to select audio output devices. 
Again this is not something universally supported as the underlying API call [`HTMLMediaElement.setSinkId`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId) is considered experimental.
- Chrome based browsers will support it natively, which also means Desktop App is covered
- On Firefox it needs to be enabled through a flag, more info at https://caniuse.com/mdn-api_htmlmediaelement_setsinkid
- No support on Safari
https://mattermost.atlassian.net/browse/MM-42497

[MM-42497] Implement audio ouputs selection

---

server/channel_state.go
server/session.go
server/sfu.go
server/slash_command.go
server/websocket.go
webapp/src/client.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/component.tsx
webapp/src/components/screen_source_modal/component.tsx
webapp/src/utils.ts

PR adds support for sending an audio track when screensharing. Turned out to be slightly more involved than anticipated due to this new track potentially conflicting with pre-existing voice tracks. We are now making the client send track ids so we can be certain of what's coming server side which makes it easy to handle everything properly.
This feature is only active if experimental features are enabled client-side. It also comes with some browser/platform limitations:
- Sharing audio only works on Chrome based browsers (no Firefox, no Safari) and only if sharing a tab, in which case only the audio from that tab is shared.
- Global system audio only works in Windows when sharing the whole screen. This applies to the Desktop App as well.
More details about audio support when screensharing …

[MM-42590] Allow sending audio track along with screensharing

---

server/activate.go
server/configuration.go
server/utils.go

A few more beta customers are hitting this as server side STUN requires an additional outgoing UDP port to be open.
PR disables server side STUN requests if the ICE host override is set. It also allows to set empty `ICEServers` which means disabling it on client side as well.
https://mattermost.atlassian.net/browse/MM-42498

[MM-42498] Disable STUN if ICE host override is set

---

webapp/src/components/recording_view/component.tsx
webapp/src/components/recording_view/index.ts
webapp/src/index.tsx
webapp/src/utils.ts

PR adds a custom recording view at `/com.mattermost.calls/recording/CHANNEL_ID`.
This is literally hacked from the existing expanded/pop out view, just removing all unnecessary parts and making the screen player as big as possible. Looking to improve further of course but I am thinking this should be good enough to enable recordings on upcoming meetings. Of course this is Community only, hence looking to merge directly on that branch.

Implement recording view

---

server/channel_state.go
server/session.go
server/sfu.go
server/websocket.go
webapp/src/client.ts

After some debugging (thanks @cpoile :raised_hands: ) and [knowledge gathering](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack) I figured out that relying on local track ids was a **dangerous** move as they are not passed consistently. Stream IDs instead seem to be the way to go, so going with those this time around. 
This solution does also remove the annoying browser specific check. The moral of the story is: I should have listened to Firefox when it told me something was clearly wrong with my intended logic. 
Oh, and this is mostly why R&D call failed so emphatically.
https://mattermost.atlassian.net/browse/MM-42737

[MM-42737] Use stream ids instead of track ids

---

server/activate.go
server/api.go
server/call.go
server/channel_state.go
server/cluster_message.go
server/configuration.go
server/plugin.go
server/utils.go
server/websocket.go
webapp/src/client.ts

PR implements a special single handler mode that allows calls to be hosted on a single instance in a HA cluster through the use of the `CALLS_IS_HANDLER=true` environment variable. This is how our community installation has been operating so far. The only relevant addition from the community branch is the extra expiry check which is needed to avoid potential issues with the state getting messed up due to the handler node crashing without cleaning up.
https://mattermost.atlassian.net/browse/MM-42574

[MM-42574] Single handler mode

---

plugin.json
server/configuration.go
server/slash_command.go
server/websocket.go
webapp/src/index.tsx

PR implements a new `/call recording` slash command that will let certain users (see `AllowedRecordingUsers`) on our Community server start/stop recordings on their own. As expected this PR is meant to go on top of `community` branch. 
These are the related changes on the recorder side: https://github.com/streamer45/calls-recorder/commit/6149291f34eba3f596cff1b9896eba741e7ece31

Implement `/call recording` slash command

---

go.mod
go.sum
plugin.json
server/activate.go
server/channel_state.go
server/configuration.go
server/plugin.go
server/session.go
server/websocket.go

PR adds the necessary logic to enable running calls through a provided `rtcd` service.
A new `RTCDServiceURL` configuration field is available of the form:
```
https://clientID:authKey@rtcd.example.com
```
When set, the plugin will offload all calls to the external service.
Note that the authentication/authorization flow is still in under review by security so it's very likely subject to breaking changes.

Implement using external `rtcd` service

---

go.mod
go.sum
server/session.go
server/websocket.go

I've tested this locally and while this is surely better than nothing, it feels like a proper solution should be either implemented on the server side or we should find a way to allow a plugin to disconnect a malicious connection. As things stand a high rate of messages will still produce some noticeable load given the events are routed to the plugin with RPC calls happening and all that's involved into that process.
Please let me know your thoughts.
https://mattermost.atlassian.net/browse/MM-42712

[MM-42712] Implement basic rate limiting for incoming WebSocket messages

---

server/activate.go
server/rtcd.go

Turned out that persisting `rtcd`'s auth store in k8s is a bit more complex than anticipated so we are allowing (tolerating really) it to reset on each pod restart. This means we need to support re-registering the client (plugin) which is what this PR is about.
This isn't ideal but hopefully it won't be needed for long as we are looking into moving to a decoupled auth service at some point.
/cc @angeloskyratzakos 
https://mattermost.atlassian.net/browse/MM-43887

[MM-43887] Attempt to re-register client if first connect attempt fails

---

webapp/src/index.tsx

PR simplifies client initialization by decoupling object creation and call to the `init()` method.
This change was done already in the [community branch](https://github.com/mattermost/mattermost-plugin-calls/blob/7a6b5645f44bd6c636857b1436e4258ff35e17fb/webapp/src/index.tsx#L356) but I forgot to add the early return check which I think allowed for this bug to happen.
https://mattermost.atlassian.net/browse/MM-43789

[MM-43789] Simplify client initialization

---

server/slash_command.go
webapp/src/client.ts
webapp/src/index.tsx
webapp/src/rtc_stats.ts
webapp/src/types/types.ts

Adding a new utility command `/call stats` to expose some client-side metrics.
Command will generate an ephemeral message with the collected metrics in JSON, e.g.:
This will be useful to debug possible client-side conditions (e.g. networking) affecting calls quality.
https://mattermost.atlassian.net/browse/MM-43660

[MM-43660] Expose some client-side metrics through `/call stats` command

---

webapp/src/components/channel_link_label/component.tsx

We were still using an hard-coded white value instead of following the theme.
https://mattermost.atlassian.net/browse/MM-43140

[MM-43140] Fix call icon color in channel link label

---

webapp/src/components/channel_link_label/component.tsx

This is why we badly need automated e2e tests :man_facepalming: 
In https://github.com/mattermost/mattermost-plugin-calls/pull/65 I used the wrong color. Now using `sidebarText` instead which makes more sense.
https://mattermost.atlassian.net/browse/MM-43140

[MM-43140] Use correct color for channel link label

---

webapp/src/components/channel_link_label/component.tsx
webapp/src/components/connected_profiles.tsx
webapp/src/utils.ts

PR implements a tooltip on the +x circle to show the remaining participants in the call.
https://mattermost.atlassian.net/browse/MM-42289

[MM-42289] Implement tooltip with participants in connected profiles component

---

build/pluginctl/main.go
server/activate.go
server/websocket.go
webapp/src/client.ts
webapp/src/components/channel_header_button/component.tsx
webapp/src/components/channel_header_button/index.ts
webapp/src/index.tsx
webapp/src/types/mattermost-webapp/index.d.ts

PR fixes a couple of issues with client state upon plugin re-initialization due to either:
- plugin disable/enable
- server restart 
This should fix the need for people to refresh every time pods rotate in Community. I tested various scenarios and everything seems okay now.
https://mattermost.atlassian.net/browse/MM-43590

[MM-43590] Simplify client state re-initialization

---

server/rtcd.go

On Cloud we want to use the installation id as client id to `rtcd`.
https://mattermost.atlassian.net/browse/MM-44361

Use `MM_CLOUD_INSTALLATION_ID` as clientID

---

webapp/src/index.tsx

Somehow the call to `fetchChannels` got lost as part of https://github.com/mattermost/mattermost-plugin-calls/pull/72.
This PR should fix the call duration issue.
I am yet unsure whether or not this relates to other issues we've been seeing today (e.g. [MM-44370](https://mattermost.atlassian.net/browse/MM-44370)). Adding a couple of log statements to help debugging those.

Call fetchChannels on plugin init

---

webapp/src/index.tsx

Resetting state in https://github.com/mattermost/mattermost-plugin-calls/pull/72 turned out to be a bit too aggressive with various side effects like the attached issue. Now resetting the whole state only if the user has disconnected from the call, otherwise simply updating it. 
At some point we'll want to send the whole current state through the websocket channel, mainly to avoid possible race conditions that could still cause inconsistencies at this point.
https://mattermost.atlassian.net/browse/MM-44370

[MM-44370] Fix state reset during ws reconnect

---

server/rtcd.go

We encountered an issue today when installing on Community servers due to a URL mismatch that was preventing the plugin to connect to `rtcd` even though stored credentials were correct. This was due to some servers not having the `MM_INSTALLATION_ID`. Either way it would be better to parse the URL regardless so to avoid any further mismatch.
PR also adds an error log in case we are on Cloud but the expected installation id is missing.

Cleanup rtcd URL from credentials

---

server/activate.go
server/rtcd.go

Just being consistent with the prefix and break it now before it becomes more expensive to do.

Use consistent prefix for environment overrides

---

server/cloud_limits.go
webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/components/custom_post_types/post_type/index.ts
webapp/src/constants.ts
webapp/src/index.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts
webapp/src/types/types.ts

- Send cloudMaxParticipants to the client so that the UI limits reflect the actual limit (overridable with the env var)
- Retrieve the cloud limit on reconnect -- if the node's limits are changed with an env var, the client will know the new limit.
- None

Send cloudMaxParticipants to the client

---

server/cloud_limits.go
webapp/src/components/channel_header_button/component.tsx
webapp/src/components/channel_header_button/index.ts
webapp/src/components/channel_header_dropdown_button/component.tsx
webapp/src/components/channel_header_dropdown_button/index.ts
webapp/src/components/custom_post_types/post_type/component.tsx

- Use dynamic limit in UI
- Improve custom post's tooltip styling
Ex of fixed custom post tooltip, and dynamic limit in UI:
- none

Use dynamic limit in UI

---

server/session.go
server/websocket.go

I forgot a `return` there which was rather important. I was likely testing with and without and erroneously pushed the wrong version. Also bumping the burst size as there were some reports of ice candidates hitting the limit.

Fix rate limit

---

LICENSE
LICENSE.enterprise
README.md
server/activate.go
server/api.go
server/audit.go
server/channel_state.go
server/client_message.go
server/cloud_limits.go
server/cluster_message.go
server/configuration.go
server/configuration_test.go
server/enterprise/LICENSE
server/enterprise/license.go
server/error_handler.go
server/log.go
server/main.go
server/performance/metrics.go
server/plugin.go
server/plugin_test.go
server/rtcd.go
server/rtcd_test.go
server/session.go
server/slash_command.go
server/telemetry.go
server/telemetry/telemetry.go
server/utils.go
server/websocket.go

PR updates project's license to our standard multi license. We are also adding a new enterprise directory covered by source available license which includes licensing checks. 
The only license guard we are adding now is to allow the plugin to initialize and use an external `rtcd` service. This feature will be available on ~~Professional (e10) and~~ Enterprise (e20) only, other than on all Cloud plans (for obvious reasons).
/cc @itao for visibility
https://github.com/mattermost/rtcd/pull/56
https://mattermost.atlassian.net/browse/MM-43921

[MM-43921] Update license

---

server/activate.go
server/api.go
server/audit.go
server/channel_state.go
server/cluster_message.go
server/configuration.go
server/session.go
server/slash_command.go
server/websocket.go
webapp/src/action_types.ts
webapp/src/actions.ts
webapp/src/components/end_call_modal/component.scss
webapp/src/components/end_call_modal/component.tsx
webapp/src/components/end_call_modal/index.ts
webapp/src/index.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts

PR introduces a new `/call end` slash command to end a call for all participants. This was made necessary as a way to fix some state issues we've been seeing lately. Originally a `cleanupState` functionality would run during plugin initialization to fix any potentially inconsistent state left by a sudden crash but this created an issue in HA deployments where one plugin instance would overwrite a perfectly healthy state on start up. Now removing the state cleanup call in case of HA deployment and relying on the end call command to fix potentially stuck calls.
Permissions wise the command is available to any system admin and to the call creator, meaning the user starting the call (aka the first participant to join).
@abhijit-singh Asking for your review since the PR introduces some minor …

[MM-44155] Implement `/call end` slash command

---

plugin.json
server/activate.go
server/configuration.go

PR reviews Calls plugin's configuration settings:
- Reworked the order and labeling of settings. 
- Prepending `(Optional)` to help text of non mandatory settings.
- Added a header with some description and link to documentation. Please let me know if we should also link on a per-setting basis. 
- Changed the plugin's display name to include the Beta word.
- Calls are now disabled by default unless MM is running on a Cloud license.
Please note that I've purposely deferred adding a setting to configure max participants per call to a follow-up ticket ([MM-44651](https://mattermost.atlassian.net/browse/MM-44651)) as it's a slightly more involved piece of work.
https://mattermost.atlassian.net/browse/MM-44560

[MM-44560] Review plugin's configuration settings

---

plugin.json
server/activate.go
server/api.go
server/cloud_limits.go
server/configuration.go
server/session.go
webapp/src/components/channel_call_toast/component.tsx
webapp/src/components/channel_call_toast/index.js
webapp/src/components/channel_header_button/component.tsx
webapp/src/components/channel_header_button/index.ts
webapp/src/components/channel_header_dropdown_button/component.tsx
webapp/src/components/channel_header_dropdown_button/index.ts
webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/components/custom_post_types/post_type/index.ts
webapp/src/index.tsx
webapp/src/selectors.ts
webapp/src/types/types.ts

PR implements a new `MaxCallParticipants` config setting to optionally limit the maximum number of participants in calls.
- For on-prem the default is 0 meaning unlimited. 
- For Cloud the default is 8. 
Config value can be also be overridden through the `MM_CALLS_MAX_PARTICIPANTS` environment variable if needed.
@cpoile I made various changes to the logic to avoid having two values for essentially the same thing. It would be great if you could do some QA on this to make sure I haven't missed anything.
https://mattermost.atlassian.net/browse/MM-44651

[MM-44651] Implement `MaxCallParticipants` config setting

---

server/activate.go
server/configuration.go
server/rtcd.go

This somehow slipped through our tests. In Cloud the config setting will be empty since we set it through env but the client was not being created unless the config value was set. Now checking for both config and env through a useful configuration getter.
https://mattermost.atlassian.net/browse/MM-44894

[MM-44894] Check rtcd URL override prior to activation

---

webapp/src/index.tsx

An error in `init()` could cause the state to be stuck, forcing the user to refresh/reopen the app since we weren't cleaning up.
https://mattermost.atlassian.net/browse/MM-44952

[MM-44952] Handle errors from callsClient.init()

---

webapp/src/index.tsx

- Don't fetch channel data if we're not in a channel.
- https://mattermost.atlassian.net/browse/MM-44919

MM-44919: Fix: Calls: Error checking channel type in global threads view

---

webapp/package-lock.json
webapp/package.json
webapp/src/actions.ts
webapp/src/cloud_pricing/modals.tsx
webapp/src/components/call_widget/component.tsx
webapp/src/components/call_widget/index.ts
webapp/src/components/channel_call_toast/component.tsx
webapp/src/components/channel_header_button/index.ts
webapp/src/components/channel_header_dropdown_button/index.ts
webapp/src/components/channel_header_menu_button/index.ts
webapp/src/components/channel_link_label/component.tsx
webapp/src/components/channel_link_label/index.ts
webapp/src/components/connected_profiles.tsx
webapp/src/components/custom_post_types/post_text.tsx
webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/components/custom_post_types/post_type/index.ts
webapp/src/components/custom_post_types/post_type_cloud_trial_request.tsx
webapp/src/components/custom_post_types/types.ts
webapp/src/components/end_call_modal/component.tsx
webapp/src/components/end_call_modal/index.ts
webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/index.ts
webapp/src/components/screen_source_modal/component.tsx
webapp/src/components/screen_source_modal/index.ts
webapp/src/components/switch_call_modal/component.tsx
webapp/src/components/switch_call_modal/index.ts
webapp/src/reducers.ts
webapp/src/selectors.ts
webapp/src/types/mattermost-webapp/index.d.ts
webapp/src/utils.ts

Moved off of `mattermost-redux` for importing types and on to the new npm package `@mattermost/types`. This should make keeping up to date with new types easier.
Did a quick find and replace and a quick package/test on my local server. Everything seemed to work like a charm.
@hmhealey let me know if I missed step or did something wrong here.

Switch to using the @mattermost/types npm package

---

webapp/package.json
webapp/tsconfig.json
webapp/webpack.config.js

Per @trilopin's comment [here](https://community.mattermost.com/core/pl/zua17j1jsfg87bfhe4bxx7r8pc) we were still importing `@mattermost/types` through the `mattermost-webapp` import instead of via npm. This PR removes those mappings.

Remove ts and webpack mappings of @mattermost/types

---

webapp/src/index.tsx
webapp/src/reducers.ts

Allowing users to join multiple calls at the same time (from separate clients). This change is mainly needed to unblock concurrent recordings on our community servers. We are still enforcing users to be connected to at most one call per client (e.g. browser tab/window).

Support joining multiple calls

---

webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/component.scss
webapp/src/components/expanded_view/component.tsx

Fixing the fill of the screen sharing icon when button is disabled (someone else is already sharing).
**Before**
**After**
https://mattermost.atlassian.net/browse/MM-45123

[MM-45123] Fix fill color for disabled state of screen share icon

---

e2e/README.md
e2e/global-setup.ts
e2e/package-lock.json
e2e/package.json

Bumped Playwright to latest, the suite is still green. The `package-lock.json` diff also includes an `npm audit fix` for https://github.com/advisories/GHSA-xvch-5gv4-984h

e2e: Update Playwright

---

webapp/src/reducers.ts

This one took some effort as for a long time I couldn't explain how a duplicate could cause all the mess reported (and seen from screenshots) and also couldn't explain the server going crazy and sending multiple events just like that. Turns out that having a single duplicate was enough to create a chain of bad DOM updates due to relying on the profile id as key in the `<li>` element. This meant the elements weren't getting deleted properly but constantly accumulating. 
To avoid all this I added some trivial deduplication check in the reducer. I understand it's far from ideal from a performance perspective but switching to anything more complex (e.g. using maps) is much more work that has its own drawbacks. I think it's okay to have this for the time being while we plan some proper redux …

[MM-42138] Avoid duplicate profiles in the redux state

---

build/manifest/main.go
go.mod
go.sum
plugin.json
server/activate.go
server/configuration.go
webapp/src/client.ts
webapp/src/selectors.ts
webapp/src/types/types.ts

Adding a new `ICEServersConfigs` config setting to support passing to clients both STUN and TURN server configs (with credentials). This is a superset of the existing `ICEServers` which we are deprecating but not removing to maintain backwards compatibility.
https://mattermost.atlassian.net/browse/MM-44486

[MM-44486] Support advanced ICE server configs through ICEServersConfigs

---

plugin.json
server/activate.go
server/api.go
server/configuration.go
server/main.go
server/plugin.go
webapp/src/index.tsx
webapp/src/selectors.ts
webapp/src/types/types.ts

PR adds support for generating short-lived TURN credentials as described in https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00#section-2.2
Addresses https://github.com/mattermost/mattermost-plugin-calls/issues/49
https://github.com/mattermost/rtcd/pull/63
https://mattermost.atlassian.net/browse/MM-45001

[MM-45001] Add support for generating short-lived TURN credentials

---

plugin.json

The json format of the ICE Servers Configurations placeholder was incorrect.

Fixed invalid json format

---

.config/notice-file/Readme.md
.config/notice-file/config.yaml

Building on https://github.com/mattermost/mattermost-plugin-playbooks/pull/1255 we continue the effort to automate `notice.txt` generation for `mattermost-plugin-calls` 
We selected `.config/notice-file` directory, to store the configuration files. Let us know if we need to relocate this. 
Ticket: https://mattermost.atlassian.net/browse/CLD-3697

[feat] Notice.txt generation configuration

---

go.mod
go.sum
server/activate.go
server/client_message.go
server/cluster_message.go
server/configuration.go
server/main.go
server/plugin.go
server/session.go
server/websocket.go
webapp/src/client.ts
webapp/src/websocket.ts

PR adds WebSocket reconnection support to the signaling channel by decoupling as much as possible the two connections (RTC and WS). What this means in practice is that a call can survive websocket disconnects and even server restarts (if using `rtcd`).
The main complexity involved here was state handling and consistency in all the various modes we support, namely:
- Single instance with plugin hosting calls (e.g. team edition).
- Single instance with `rtcd` hosting calls.
- HA cluster with plugin hosting calls, load balanced across the nodes.
- HA cluster with single node hosting the calls.
- HA cluster with `rtcd` hosting calls.
Before this PR, upon websocket disconnect we would cleanup everything related to a session, closing the RTC channel, and cleaning up the state. To support …

[MM-43838] WebSocket reconnection support

---

.gitlab-ci.yml
e2e/playwright.config.ts

Minor config update to support reporting statuses back to Github. Examples can be seen in the recent commit checks on this branch.
Also a note for the moment, mirroring from Github -> Gitlab currently happens every 30 minutes so the new check won't always appear immediately. This will change after [DOPS-1131](https://mattermost.atlassian.net/browse/DOPS-1131) is handled.

e2e: Gitlab -> Github status reporting

---

webapp/src/components/call_widget/component.tsx

This is not the kind of fix I like to merge but after some consideration I decided to go ahead with it since the implementation effort for a properly fix would be significant and this simple hack covers the main use case (joining calls in DMs/GMs). Looking to address the underlying problem in [MM-46048](https://mattermost.atlassian.net/browse/MM-46048) 
**Context**
This is a [well-known](https://www.ietf.org/proceedings/82/slides/rtcweb-10.pdf) problem with WebRTC signaling and a [pretty decent solution](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation) has been devised already. Unfortunately this is not supported by either the server side implementation (pion), nor our version of the mobile native dependency (implemented in …

[MM-45977] Workaround to prevent signaling race

---

webapp/src/components/expanded_view/component.tsx

Had a couple more reports of this unexpected behaviour so decided to fix it since it's trivial. Video can still be paused if necessary by using the available controls.
https://mattermost.atlassian.net/browse/MM-44949

[MM-44949] Disable video pause by clicking on screen sharing player

---

webapp/src/components/call_widget/component.tsx

Just fixing the display of long names in the widget.
Before
After
https://mattermost.atlassian.net/browse/MM-45110

[MM-45110] Fix overflow for long names

---

webapp/src/components/call_widget/component.tsx
webapp/src/index.tsx
webapp/src/utils.ts
webapp/src/vad.ts

This was an interesting one. It started with just some hard to explain high CPU usage in Firefox (I usually test stuff locally on a Chrome + Firefox setup). Then in the last few days I was getting random issues with my audio service (`pulseaudio`) not being able to playback. Closing the Chrome tab I was testing Calls on temporarily fixed this odd behaviour. 
But it was only today, after failing once again to hear people due to a playback failure that I realized I was leaking dozens of audio resources that were still in the playback state even long after ending calls. 
PR reviews and fixes any outstanding leak of audio resources.
@lieut-data I just couldn't believe that it was simply a Linux quirk, so dug further, thank you :grin: 
https://mattermost.atlassian.net/browse/MM-46107

[MM-46107] Fix audio resources leaks

---

go.mod
go.sum
server/rtcd.go
server/session.go
server/websocket.go

Two main changes here to avoid leaking the `handleJoin` goroutine:
- Handling the new `ClientMessageClose` event that gets sent by `rtcd`.
- Exiting from `wsReader`/`handleLeave` `select` blocks when the `rtcCloseCh` gets closed.
It's important to notice that this PR does not fix the race but simply makes it much more unlikely to cause a leak. This is because the logic is non trivial and serializing everything using a mutex feels like an excessive constraint just to cover a rare edge case so we allow this to happen but react accordingly.
https://github.com/mattermost/rtcd/pull/68
https://mattermost.atlassian.net/browse/MM-46124

[MM-46124] Improve session deinitialization

---

webapp/src/components/call_widget/component.tsx

Quickly ending a call before the timer fires would cause the reported error.
https://mattermost.atlassian.net/browse/MM-46291

[MM-46291] Fix possible undefined access

---

webapp/package-lock.json
webapp/package.json
webapp/src/client.ts
webapp/src/rtcpeer/index.ts
webapp/src/rtcpeer/types.ts

Some recent issues (e.g. [MM-45977](https://mattermost.atlassian.net/browse/MM-45977)) surfaced a need to have more control on lower level APIs of WebRTC connections. Moreover, future work (e.g. implementing simulcast) will pose similar needs as well .
I decided to spend part of last Open Source Friday to replace `simple-peer` with our own version of a WebRTC connection wrapper (which I should have probably named simpler-peer :p). Pun aside, `simple-peer` let us focus on delivering calls in a very efficient way without worrying too much about anything low level on the client side of which I am very grateful :raised_hands: . 
That said, I feel this is the right time to move on, especially with mobile v2 support going live soon. What this means, in practice:
- Lighter implementation (~150 …

Replace `simple-peer` with `RTCPeer`

---

webapp/src/actions.ts

This PR adds the ability to know in which component the purchase modal opening was initiated from
https://mattermost.atlassian.net/browse/MM-45761
https://mattermost.atlassian.net/browse/MM-45014
https://github.com/mattermost/mattermost-webapp/pull/10920
```release-note
NONE
```

[MM-45761] - Telemetry: Track how many users end up in purchase/pricing modal/notify admin

---

webapp/src/components/call_widget/call_duration.tsx
webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/component.tsx

This was a low hanging fruit especially as we are trying to optimize the widget to be as performance as possible.
**Before**
**After**
https://mattermost.atlassian.net/browse/MM-42395

[MM-42395] Extract call duration to avoid unnecessary parent component re-render

---

webapp/src/client.ts
webapp/src/components/call_widget/component.tsx
webapp/src/types/types.ts

This is probably the way it should have been implemented since the start. We relay the `devicechange` event to the component to keep everything in sync and avoid having to constantly poll. This has the added bonus that the menu will update even when fully open and visible.

Relay `devicechange` event to properly sync devices

---

webapp/src/rtcpeer/index.ts

Yet another browser inconsistency. Today I learned that Firefox does not implement the [`RTCPeerConnection.onconnectionstatechange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionstatechange_event#browser_compatibility) so the event was never firing. Switching to use the more widely adopted `oniceconnectionstatechange` instead.
https://mattermost.atlassian.net/browse/MM-46501

[MM-46501] Fix connect event not firing

---

webapp/src/client.ts
webapp/src/index.tsx
webapp/src/types/types.ts

We use [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) to temporarily store statistics for the last call the user has joined. This way the `/call stats` slash command can return useful information even after leaving a call.
/cc @lieut-data 
https://mattermost.atlassian.net/browse/MM-46476

[MM-46476] Temporarily persist stats for last call

---

webapp/src/action_types.ts
webapp/src/index.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts
webapp/src/types/types.ts

PR disables the "user has joined the call" sound after reaching a threshold of 8 participants. 
Since we are looking to make this configurable at some point in the future, I opted not to check against a simple constant but add the necessary boilerplate to support the more advanced use case.
/cc @tanmay-des @itao 
https://mattermost.atlassian.net/browse/MM-45128

[MM-45128] Disable join sounds after number of participants threshold

---

e2e/global-setup.ts
e2e/tests/start_call.spec.ts
webapp/src/action_types.ts
webapp/src/components/channel_header_button/index.ts
webapp/src/components/channel_header_dropdown_button/index.ts
webapp/src/components/channel_header_menu_button/index.ts
webapp/src/index.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts

PR adds an error message in case `/call start` or `/call join` slash commands are sent in a channel where calls are not enabled. As an added bonus this PR led to some small refactor on the redux side.
https://mattermost.atlassian.net/browse/MM-46099

[MM-46099] Return error on joining call through slash command if calls are disabled

---

server/websocket.go
webapp/src/components/channel_header_button/component.tsx
webapp/src/components/channel_header_button/index.ts
webapp/src/components/channel_header_dropdown_button/component.tsx
webapp/src/components/channel_header_dropdown_button/index.ts

PR disables calls in archived channels. While technically nothing was preventing them up until now, the client would error out.
We are now disabling the Start/Join button and providing some information on hover.
What's potentially left to handle is the automatically joining through URL case. With the error fixed nothing would happen upon visiting the URL. If we'd like to be more informative we may consider opening up a modal or give some other kind of feedback to the user. Let me know your thoughts.
/cc @itao 
https://mattermost.atlassian.net/browse/MM-46412

[MM-46412] Disable calls in archived channels

---

server/slash_command.go
webapp/src/index.tsx

So it wasn't the quotes but the audio device labels containing spaces that would mess the output of `strings.Fields`. Sending a base64-encoded payload to avoid this kind of issues.

Use base64 payload

---

server/rtcd.go

This is one bit of confusing syntax I wanted to get rid of. Using the telemetry ID as a fallback seems to be a good choice as it's saved in DB already and unique across the cluster.
This means the `RTCD service URL` setting can be now configured simply using the `http://hostname:port` form.
https://mattermost.atlassian.net/browse/MM-46918

[MM-46918] Fallback to using telemetry ID as rtcd's client ID

---

server/api.go
server/telemetry.go
webapp/.eslintrc.json
webapp/src/actions.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/call_widget/index.ts
webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/index.ts
webapp/src/types/telemetry.ts

PR implements client side telemetry through a new `/telemetry/track` API endpoint. This doesn't instrument any path yet but merely provides the generic functionality to track events. Will send a PR that builds on top of this one for that.
To be used as such:
```js
trackEvent('user_toggle_participants_list', 'widget');
```
https://mattermost.atlassian.net/browse/MM-46807

[MM-46807] Implement client-side telemetry

---

plugin.json

- change custom to text
- tested, works
- https://mattermost.atlassian.net/browse/MM-46947

MM-46947 - Fix: Manifest parsing won't allow placeholders for custom pluginSettingType

---

server/client_message.go
server/websocket.go
webapp/src/client.ts

This PR adds the minimum logic to listen for reaction events sent by the client and broadcast them to the users in the call.
I also added a second commit (sorry for the force-push, I had to fix some typing there :nerd_face:) with an endless loop of emoji reactions sent by every client that joins the call. This will be removed as soon as the emoji picker is in place.
--

Reaction websocket broadcast

---

webapp/src/components/expanded_view/component.tsx

Fix the grinning emoji and fix emoji version for emoji picker. The data prop is actually not needed and it overrides the emojiVersion prop.
Grinning emoji:
Emoji picker (no more v14 emojis)

Minor bug fixes

---

webapp/src/reducers.ts

The logic of removing reactions was working good, but I was overwriting the whole state map, that contains the array of reactions for each channel, with the array of reactions of a single channel. So this was not only removing all reactions in a call, but *in every call* :facepalm: 
--

Fix bug that made all reactions in the stream disappear

---

webapp/src/components/expanded_view/component.tsx
webapp/src/components/reaction_stream/reaction_stream.tsx

Absolutely position the reaction list inside the parent div so that it does not shift the placement of any other siblings. The `flex-direction` is no longer needed in the parent, so I removed it.
https://user-images.githubusercontent.com/3924815/192263536-f1017d92-a58f-4a66-9ec3-e09aebd1385a.mp4
--

Fix horizontal shift when adding reactions

---

e2e/tests/shortcuts.spec.ts
webapp/src/components/call_widget/component.tsx

Keyboard shortcut to mute/unmute is causing a conflict with the accessibility controller since the [recommended behaviour](https://www.w3.org/WAI/ARIA/apg/patterns/button/) is that `Space` toggles a button in focus.
Given we are providing specific shortcuts I am thinking accessibility is retained hence preventing this behaviour by unfocusing the button element on click and let the in-product shortcut do its thing. But I am happy to revisit, just let me know your thoughts.
More context can be found in the original discussion at https://community.mattermost.com/core/pl/r9rktsydz3ndmmdqyjkicb8i6o
https://mattermost.atlassian.net/browse/

[MM-47001] Fix accessibility conflict

---

webapp/src/components/expanded_view/component.tsx
webapp/src/components/reaction_stream/reaction_stream.tsx

Create the hands up array in the same order as the participants list RHS, so hands up are shown in the order that they were raised. Also changed the background colour to white.

 Make consistent order of hands up 

---

webapp/src/components/call_widget/widget_button.tsx
webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/controls_button.tsx
webapp/src/components/shared.tsx

There doesn't seem to be a clean way to prevent the `OverlayTrigger` from rendering so I am using css to avoid doing some weird code duplication or more complex stuff (wrapping the element).
https://mattermost.atlassian.net/browse/MM-47364

[MM-47364] Disable crash on hovering disabled button

---

webapp/src/components/expanded_view/component.tsx
webapp/src/index.tsx

- increased timer for reaction disappearance to 10 secs
- emoji picker focus on search bar on opening
- emojis per line 9 -> 12
no longer requiring `/calls experimental on` as in https://github.com/mattermost/mattermost-plugin-calls/pull/214

Qol no experimental

---

webapp/src/components/expanded_view/component.tsx

Controls were disappearing when there are many users on a call
Before
----
https://community.mattermost.com/core/pl/gsm1s4ubc38m5py4q3zf4pw5py
After
----

Fix participant screen overflow

---

go.mod
go.sum
webapp/src/rtc_stats.ts

Forgot to do this as part of https://github.com/mattermost/mattermost-plugin-calls/pull/231. While I was testing locally I also added a couple of useful stats to the report.

Bump `rtcd` dependency to v0.7.0

---

webapp/src/action_types.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/index.tsx
webapp/src/reducers.ts

PR fixes a couple of state related issues in the main window when using the global widget, namely:
- Channel toast should not show after joining the call.
- Leave button should render in the post card.
- Leaving the call from the post card should be allowed, as well as through slash command.
- Switching calls from the post card should work as in web.
https://github.com/mattermost/desktop/pull/2349
https://mattermost.atlassian.net/browse/MM-48142

[MM-48142] Fix remaining call state issues on parent window

---

webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/component.tsx

I remember spending some good time on implementing this logic but looking back at it now it seems overly complex and easily error prone. I think relying on track ids to figure out if something has changed is a better approach which seems to be working fine.
This PR should fix https://mattermost.atlassian.net/browse/MM-48351 as well.
https://mattermost.atlassian.net/browse/MM-48351

[MM-48351] Fix screen stream flakyness

---

server/channel_state.go
server/recording_api.go
webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/in_call_prompt.tsx
webapp/src/types/types.ts
webapp/src/utils.ts

PR adds some basic error handling to cover for the following failure cases:
1. Recording fails to start immediately (e.g. job service returns an error).
2. Recording job times out (e.g. recording bot fails to join the call).
3. Recording fails to stop.
@tanmay-des I opted to actually relay the server side error to the client in the hope it will give them more information but I also acknowledge it's not really actionable on their part as they likely need a system/infrastructure admin to intervene. Please let me know if you'd like it reverted to the generic "something has failed".
/cc @itao 
https://mattermost.atlassian.net/browse/MM-48746

[MM-48746] Implement basic error surfacing

---

server/session.go

Fixing a potential edge case where in case of a timeout (or other unexpected error) while making the start job request, the recording job process could still run and the bot start recording without anyone noticing. So we add an explicit check to make sure the bot is only allowed in if a recording has been requested but not started yet.

Fix potential edge case

---

webapp/src/components/call_widget/component.tsx
webapp/src/components/call_widget/index.ts
webapp/src/components/call_widget/widget_banner.tsx
webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/controls_button.tsx
webapp/src/components/expanded_view/in_call_prompt.tsx
webapp/src/components/expanded_view/index.ts
webapp/src/components/expanded_view/recording_info_prompt.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts

PR addresses some outstanding UX feedback (see https://www.figma.com/file/9HL2HADCQ0lLmn1RBOBGGV/Calls%3A-Recording?node-id=298%3A120956&t=0Aq13EORRxvt3YoH-0 for details).
In addition we are at least partially addressing the issue of a user not being aware of becoming the host. We are showing the "you are recording this call" banner again upon host change even if the banner was dismissed prior (as non-host user). Ideally we should consider a custom message for this but we didn't get time to design further so happy to have something rather than nothing.
https://mattermost.atlassian.net/browse/MM-48928

[MM-48928] Outstanding UX for recordings

---

server/session.go
server/websocket.go

Almost randomly spotted this while testing recordings. Users were leaving calls but it was not reflected in the recording view and in the output file as a result. 
We need to make extra sure to always use the provided `publishWebSocketEvent` wrapping method so that the call bot receives the ws events.

Fix missing ws events

---

server/job_service.go
server/rtcd.go

PR fixes an issue causing the plugin to fail to start if the provided URL (either `rtcd` or `calls-offloader`) has a trailing slash.
Thanks @oh6hay for spotting this :100:

Fix trailing slash in services URLs

---

webapp/src/constants.ts

- Change the error message so it's not so frightening if they just pressed 'cancel'
- https://mattermost.atlassian.net/browse/MM-47358

MM-47358 - Fix: Cancelling screen sharing results in "system preferences" client side error

---

webapp/src/components/call_widget/component.tsx
webapp/src/rtcpeer/index.ts

PR implements glare-free negotiation using the proposed scheme in https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation (polite peer case).
In practical terms this avoids a whole set of issues involving clients receiving tracks while trying to send theirs. The most glaring example we have in product would be joining calls unmuted, which led to the unfortunate "sleep a few seconds" hack.
I've load tested a bit to cover a few scenarios and it seems like working as expected. I am still not entirely sure whether this covers all potential racing issues with signaling but it definitely improves the most common ones.
https://github.com/mattermost/rtcd/pull/80
https://mattermost.atlassian.net/browse/MM-46048

[MM-46048] Implement glare-free negotiation

---

go.mod
go.sum
plugin.json
server/rtcd.go
server/utils.go
server/utils_test.go

PR implements a minimum supported version compatibility check for `rtcd` that will prevent the plugin from starting if the configured (in manifest) minimum version is not respected. Such error will be surfaced to the admin through the admin console (see screenshot).
https://github.com/mattermost/rtcd/pull/84
https://mattermost.atlassian.net/browse/MM-49022

[MM-49022] Implement minimum supported version compatibility check for `rtcd`

---

server/bot_api.go
server/channel_state.go
server/session.go
webapp/src/components/custom_post_types/post_type/component.tsx

I found a couple of issues while implementing this:
1. Multiple recording files were not saved correctly in post props due to a type mismatch.
2. There was a potential race condition in a rapid sequence of stop recording -> start recording that would lead to an invalid state with the host and users thinking a seeing the new recording as ended while ongoing.
3. Fixed a potential state parsing bug due to improper key length check.
As far as UX changes so far I only implemented a simple indicator of available recordings, no extra behaviour as there are some inconsistencies with the design so anything more will require further input.
https://mattermost.atlassian.net/browse/MM-48900

[MM-48900] Display available recording files in call thread root post

---

server/job_service.go
standalone/src/common.ts

Two main things happening here:
1. Passing the bot token used to record through URI fragment instead of query. I am doing a bit more to try and keep it extensible so we are actually passing a base64 encoded json object with the token inside.
2. We bump the recorder image to `v0.2.2` (still to be released, pending a couple of review on that side). 
https://github.com/mattermost/calls-recorder/pull/13
https://mattermost.atlassian.net/browse/MM-49635

[MM-49635] Improve recordings security

---

server/rtcd.go

PR addresses a potential corner case that would lead to getting a registered client unable to login. If the URL to rtcd changed but the target instance was kept the same (e.g. only the hostname changed), the client would attempt to register again and get a conflict error, resulting in the plugin permanently failing to start.
We slightly alter this behaviour to allow the client to authenticate first and only attempt registration if that fails.
https://mattermost.atlassian.net/browse/MM-46887

[MM-46887] Improve rtcd client auth logic if URL changes

---

webapp/src/shortcuts.ts

This happened to me before but I wasn't quite sure how to reproduce. Apparently, selecting one of browser's saved suggestions on a text input generates a keydown event with no key nor code. PR adds some extra checks to make sure we don't try to read from undefined.
https://mattermost.atlassian.net/browse/MM-49674

[MM-49674] Add undefined checks to keyboard shortcuts handler

---

webapp/src/components/call_widget/component.scss
webapp/src/components/call_widget/component.tsx

PR fixes especially long audio devices lists from overflowing outside the viewport. To achieve this we are doing two things:
1. Setting a `max-height` to be the height of widget + height of menu.
2. Making the submenus always start from the top.
Originally I tried to make them grow upwards but that would break the global widget logic and required even more complex calculations. I think this approach is simple enough since it doesn't make sense to grow indefinitely anyway.
Since I was touching the code I opted to add a background to help the user identify what list they currently have open.
Before
After
https://mattermost.atlassian.net/browse/MM-49588

[MM-49588] Fix audio devices list overflow

---

standalone/src/init.ts
webapp/src/types/types.ts
webapp/src/websocket_handlers.ts

We need to check for in payload channelID  when receiving an event since the calls bot may not be in a channel so `broadcast.channel_id` won't be useful.

Fix websocket handlers

---

webapp/index.d.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/call_widget/index.ts
webapp/src/index.tsx
webapp/src/utils.ts

- Split into two commits, one related, one formatting
- Only the widget's participant list will consider reactions when sorting (otherwise the other participant lists would be shifting around a lot, and those contexts have the reaction stream to show recent reactions)
- Priority is still presenter > hand raised > unmuted > reaction
- https://mattermost.atlassian.net/browse/MM-49709

[MM-49709] Emojis in the widget participant list

---

webapp/src/components/call_widget/component.tsx

Sending a focus event to the desktop side since the window is not focused automatically when opened from the global widget.
https://github.com/mattermost/desktop/pull/2539
https://mattermost.atlassian.net/browse/MM-49739

[MM-49739] Send focus desktop event

---

server/slash_command.go
webapp/src/components/badge.tsx
webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/recording_info_prompt.tsx
webapp/src/index.tsx

PR adds support for using `/call recording [start|stop]` to handle call recordings.
For these to make sense I also added a couple of missing flows from the widget, such as async error handling and loading spinner when starting a recording.
https://github.com/mattermost/mattermost-mobile/pull/7062
https://mattermost.atlassian.net/browse/MM-49996

[MM-49996] Add `/call recording` slash command

---

webapp/src/index.tsx

We were failing to dispatch the call start event when fetching call (and channel) data. This bug was easily reproducible by logging out and back in with an ongoing call. I cannot guarantee that's what happened to all the reporting users but these changes should likely fix most instances of the issue.
https://mattermost.atlassian.net/browse/MM-49944

[MM-49944] Dispatch missing call start event

---

webapp/src/client.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/call_widget/index.ts
webapp/src/components/call_widget/loading_overlay.tsx

PR fixes a long lasting bug causing a failure when joining a call. After some inspection I realized the problem wasn't the missing channel but the fact that the client doesn't know if it's connected due to not receiving the ws event for the current user. This could happen when someone tries to connect to a call during a ws reconnection attempt (e.g. just coming back from a laptop sleep). The end result would be very confusing, with the widget not showing while actually being in a call (e.g. hearing everyone but no UI).
The simplest (although not perfect) fix here is to use the channelID from the calls client as source of truth and trust that we are going to connect, eventually.
https://mattermost.atlassian.net/browse/MM-42233

[MM-42233] Fix widget crash on joining calls

---

webapp/src/components/call_widget/component.tsx

- Chrome is where this problem can happen: it returns default devices as a separate device. I don't think this is a problem, and is probably helpful (so the user knows that that particular device is their usual default). So, instead of deduping (they will have the same `groupId`), let's ensure that the default is labelled as default. In the ticket, this didn't happen, and that's where the confusion came from. But if it was labelled "Default - Airpods" and "Airpods", that would make sense. I think. What do you think?
- Aside: while testing today, it always had the "Default - " prefix. Maybe that's a recent Chrome change, or I did something to cause the screenshot seen in the ticket. Either way, this will prevent that from happening again.
- Safari won't ever have this trouble, because it's …

MM-42564 - Audio Output for Airpods shows two outputs

---

lt/client.go

`pion` doesn't yet support the updated API that allows for perfect negotiation so we have to resort to some hack to mitigate the issue.
To fix the `SetRemoteDescription failed: InvalidModificationError: invalid proposed signaling state transition: have-local-offer->SetRemote(offer)->have-remote-offer` error we detect the conflict and queue the offer for later on.

Mitigate some glare in load-test client

---

lt/client.go

As part of improving the simulation I added some code to send a picture-loss-indication when receiving a track, similarly to what a real client (e.g. browser) would do. However I forgot to add a check on the track type so now we are sending them out for audio tracks as well which doesn't make sense and also causes an error spam on the server side.

Fix load-test client from sending PLIs for voice tracks

---

e2e/playwright.config.ts
standalone/src/widget/index.tsx
webapp/src/components/call_widget/component.tsx
webapp/src/components/screen_source_modal/component.tsx

PR adds some logic to handle screen permissions error coming from the desktop side so that they get surfaced to the user same as on web.
https://github.com/mattermost/desktop/pull/2554
https://mattermost.atlassian.net/browse/MM-46696

[MM-46696] Surface screen permissions error coming from global widget desktop window

---

webapp/src/components/expanded_view/component.tsx

- Previously, clicking links in the RHS of the desktop popout did two things:
- For internal links, nothing happened.
- For external links, a new electron window would open:
- Now (with https://github.com/mattermost/desktop/pull/2558) the links are handled completely by the Desktop app.
- https://mattermost.atlassian.net/browse/MM-49079

MM-49079 - Fix desktop links

---

webapp/src/components/screen_source_modal/component.tsx

There was an issue in handling the request from the desktop side in the `ScreenSourceModal` component since in case of an error we wouldn't show the modal but its state would still be open. Handling the error fixes this so that if users hide the "no permissions" banner and try again to share they will get it again, as expected.
To note, I think we should be changing the error message if we are on desktop since the "cancelled" part doesn't apply there. 
https://github.com/mattermost/desktop/pull/2556

Handle screen permissions error to hide component

---

standalone/src/init.ts
standalone/src/widget/index.tsx
webapp/src/action_types.ts
webapp/src/actions.ts
webapp/src/components/call_error_modal.tsx
webapp/src/index.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts

PR adds some logic to propagate client blocking errors (e.g. connection failures) to the desktop side since the global widget window gets closed immediately but we want to show a modal. I also took the opportunity to simplify a bit. I was originally storing the client error because I was unaware we could pass props to the modal but this is much cleaner.
https://github.com/mattermost/desktop/pull/2557
https://mattermost.atlassian.net/browse/MM-49089

[MM-49089] Propagate blocking errors to desktop

---

webapp/package-lock.json
webapp/package.json
webapp/src/index.tsx

- Batch the actions on connect/reconnect
- This requires a little bit of awaiting on the client, but I don't think this is an issue, and the overall gain is likely far higher.
- Just on my local dev server this batches 47 actions on reconnect. Probably a much better improvement on a server like community with more channels using calls.
- https://mattermost.atlassian.net/browse/MM-50542

MM-50542: Improve performance on connect/reconnect

---

webapp/src/components/call_widget/component.tsx

It doesn't make sense to let the thumbnail grow indefinitely in height as it ends up covering more of Mattermost.
https://mattermost.atlassian.net/browse/MM-50541

[MM-50541] Limit screen thumbnail height

---

standalone/src/recording/components/recording_view/index.tsx
webapp/src/client.ts
webapp/src/components/call_widget/component.tsx

This was an interesting one given I could never reproduce the issue on my end, neither locally nor when connecting on remote instances.
The bug has been there for a long time as I remember first encountering this on a Community recording a few months ago. Something in the recorder setup made it more likely to reproduce. In fact, I was finally able to do this earlier today through a quick load-test on Community.
The problem was that we are registering the media track events handler(s) when mounting the component (both widget and recording view) but any delay in doing so could mean events firing before we get a chance to listen and tracks getting "lost", or better, never attached to the document, hence never played. To fix this, before listening on the track events we also check for …

[MM-50751] Fix race condition attaching media tracks on join

---

webapp/src/components/admin_console_settings/ice_host_override.tsx
webapp/src/components/admin_console_settings/udp_server_address.tsx
webapp/src/components/admin_console_settings/udp_server_port.tsx

Should fix #344 
I couldn't reproduce this but looking at the failing logs there's a chance the `Plugins` object is not immediately initialized when loading the component so guarding against it should be enough to fix this and allow it to render as soon as available, unless of course there's also something broken on the webapp side.
https://mattermost.atlassian.net/browse/MM-50943

[MM-50943] Prevent possible access to undefined object

---

server/rtcd.go

PR fixes a couple of issues, main one being that failing the min version check didn't properly close the client. This was totally fine if the attempt happened during plugin startup because we would error out on activation and essentially stop the plugin. But if `rtcd` instances were to be updated with a *live* plugin the reconnect logic would go ahead and continuously fail the version check and leak a new client on each attempt. On Community today we reached 750 ws clients due to this "misbehaviour".
And the reason this issue originally triggered was that the build version was not one of the accepted ones. We were testing latest changes which resulted in the build version being `master` but we would only skip the check for either empty strings or those starting with `dev`. 
Finally, the …

[MM-50990] Fix potential rtcd client leak

---

webapp/src/index.tsx
webapp/src/slash_commands.tsx

PR refactors the slash commands handler in order to let other plugins (Playbooks in today's case) to easily start/stop calls from the client side.
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1816
https://mattermost.atlassian.net/browse/MM-50623

[MM-50623] Allow to run Calls slash commands from other plugins/products

---

webapp/src/actions.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/recording_info_prompt.tsx
webapp/src/reducers.ts
webapp/src/types/types.ts
webapp/src/websocket_handlers.ts

PR fixes a couple of issues with recordings info prompts:
1. In case of error starting the call, if the banner was dismissed once, any successive attempt to start a call would not show anything in case of error.
2. Not clearing the recording state on disconnect made it so that if a prompt was shown before leaving a call it would briefly reappear (almost like a flicker) on joining a new call. 
https://mattermost.atlassian.net/browse/MM-51288

[MM-51288] Surface recording errors if happening after first dismissal

---

webapp/src/components/reaction_stream/reaction_stream.tsx

- Simple fix
- https://mattermost.atlassian.net/browse/MM-51007

MM-51007 - Fix: CSS raise hand z-index incorrect

---

server/websocket.go
webapp/src/components/expanded_view/reaction_button.tsx
webapp/src/types/types.ts

- The change to `emoji-picker-react` changed the emoji names a bit, and some emojis are not in the emoji name map on the mobile side. So, replace spaces in the names with underscores, and send the emoji literal string in case the map doesn't have the emoji name.
- https://mattermost.atlassian.net/browse/MM-51226

MM-51226 - Mobile: Emojis not showing in reaction stream

---

server/session.go
server/websocket.go
webapp/src/reducers.ts

@cpoile I looked at logs and there's nothing suggesting the event wasn't sent so I must assume it either got lost somehow or your client didn't receive it for some unrelated reason. I moved the server side logic to a better place but other than that nothing has changed on that side.
I am opting for adding a fallback on the client since we can safely assume that a disconnection means the screen sharing state should be cleared. That said, if websocket events are failing to get to clients, we clearly have more serious problems to deal with.
https://mattermost.atlassian.net/browse/MM-51322

[MM-51322] Add fallback logic for disconnected presenter

---

webapp/src/components/custom_post_types/post_type/component.tsx

Compass icons striking again...this time I couldn't reproduce this outside of Community, even loading the same webapp version so maybe there's something else loading overriding definitions. Either way the problem is that on Community we have a `.CompassIcon` class changing the display to `flex` which causes the element to incorrectly wrap. 
https://mattermost.atlassian.net/browse/MM-51405

[MM-51405] Fix bad alignment of file recordings icon

---

standalone/src/recording/components/recording_view/index.tsx

There is a chance that the screen sharing track gets received before the video player element gets mounted in the DOM which would result in missing the chance to attach the video source. This was spotted during performance testing I am running as several recordings were completely missing the screen content.
https://mattermost.atlassian.net/browse/MM-51483

[MM-51483] Fix potential failure in rendering screen sharing track

---

standalone/src/recording/index.tsx

Not the first time this hit me. The events sent to the bot are not broadcasted for obvious reasons so the channelID will be sent as part of the data. Profile pictures were failing to get stored properly and the component wouldn't render, causing the weird behaviour.
https://mattermost.atlassian.net/browse/MM-51500

[MM-51500] Use correct channelID when setting profile pictures in store

---

webapp/src/index.tsx

We were still registering and mounting the `ExpandedView` every time we joined a call even if it was never going to be rendered, with the exception of Desktop < 5.3. Adding some checks to make sure it's mounted only in such case.

Remove unnecessary mount

---

standalone/src/common.ts
standalone/src/init.ts
webapp/src/index.tsx

PR adds missing support for starting a call from a thread on the Desktop app. It boils down to passing the thread id properly.
https://github.com/mattermost/desktop/pull/2630
https://mattermost.atlassian.net/browse/MM-51532

[MM-51532] Add support to start a call from existing thread on Desktop app

---

webapp/src/utils.ts

- Participants who raised their hands first will always be ordered first, maintaining the raised hand order regardless of other states (e.g., voice on).
- Mobile: https://github.com/mattermost/mattermost-mobile/pull/7229
- https://mattermost.atlassian.net/browse/MM-50533

MM-50533 - Prioritize raised hand when ordering participants

---

.github/workflows/cd.yml

- Trying to fix the broken cd pipeline
- https://mattermost.atlassian.net/browse/MM-51985

MM-51985 - Fix for: Rudder keys are missing from prod builds

---

.github/workflows/cd.yml
Makefile

- use the newly added env vars from https://github.com/mattermost/actions-workflows/pull/27
- https://mattermost.atlassian.net/browse/MM-51985

MM-51985 - Fix: Rudder keys are missing from prod builds

---

webapp/src/components/call_widget/component.tsx

Making widget top menus draggable. This means participants list, screen sharing panel or the settings menu. Buttons are still an exception that stands and won't be draggable.
/cc @tanmay-des @lieut-data 
https://user-images.githubusercontent.com/1832946/231522478-c74b81b9-79da-43cb-b511-b3fc2d682c50.mp4

Make widget menu(s) draggable

---

webapp/src/components/call_widget/component.tsx

Setting the menus as draggable in https://github.com/mattermost/mattermost-plugin-calls/pull/400 had the unfortunate side effect of preventing any sort of mouse event from going through, including scrolling. 
PR will partially revert that in order to restore the expected scrolling functionality. We are stll keeping the menu header as draggable but the actual items won't be. I think that should be acceptable as it doesn't require having to resort to potentially complex workarounds.
Thanks once more to @lieut-data for spotting this.
https://mattermost.atlassian.net/browse/MM-52497

[MM-52497] Restore participants list scrollability in global widget

---

webapp/src/components/call_widget/widget_banner.tsx

Similar issue to https://github.com/mattermost/mattermost-plugin-calls/pull/410 . We need to explicitly set `app-region: no-drag` in order for the element to be clickable.

Fix close button on global widget banner

---

e2e/tests/shortcuts.spec.ts
e2e/tests/types.ts
webapp/src/client.ts
webapp/src/components/call_widget/component.tsx
webapp/src/components/call_widget/join_notification.tsx
webapp/src/components/expanded_view/component.tsx
webapp/src/index.tsx
webapp/src/websocket.ts

PR introduces a couple of changes to how we store and render local state, specifically muted/unmuted and raised/lowered hand. This is an effort to mitigate potential inconsistencies in case of unreliable network causing websockets events to be delayed, or worse, lost.
https://mattermost.atlassian.net/browse/MM-48095

[MM-48095] Mitigate potential inconsistencies with local client state

---

standalone/src/recording/index.tsx
webapp/src/components/expanded_view/component.tsx

As discussed in https://community.mattermost.com/core/pl/jokj8sb6fpga7fyfh3txfbsara we are going to use `sidebarBg` to improve support on custom themes.
I suppose this may need updating on the mobile side but should be trivial.

Use sidebar bg to generate calls bg

---

e2e/constants.ts
e2e/global-setup.ts
e2e/global-teardown.ts
e2e/package-lock.json
e2e/package.json
e2e/tests/global_widget.spec.ts
e2e/tests/join_call.spec.ts
e2e/tests/media.spec.ts
e2e/tests/popout.spec.ts
e2e/tests/recordings.spec.ts
e2e/tests/shortcuts.spec.ts
e2e/tests/start_call.spec.ts
e2e/tests/switch_call.spec.ts
e2e/tests/types.ts
e2e/types.ts
e2e/utils.ts

PR refactors a bit how we are handling users state in e2e tests. Originally we'd be using a constant array for simplicity but that wasn't ideal so we are removing that and rely on the state of the server instead by generating usernames on the fly through the expected pattern (`calls-user` prefix + test index).
https://mattermost.atlassian.net/browse/MM-52604

[MM-52604] Refactor e2e users state generation

---

webapp/src/components/connected_profiles.tsx

PR currently fixes the inconsistency but as @matthewbirtch suggested, it would be good to do a revision of all the places where we display participants names and check whether we should apply user display settings:
@tanmay-des Could you help with this? Some of the places would be:
- Participants list (both widget and expanded view)
- Participants grid (expanded view)
- Connected profiles in channel toast tooltip
- Connected profiles in chat thread root post tooltip
- Connected profiles in sidebar active call icon tooltip
- Reaction stream
https://mattermost.atlassian.net/browse/MM-52648

[MM-52648] Fix inconsistent participant name display in channel toast

---

webapp/src/components/admin_console_settings/rtcd_service_url/index.tsx

I was playing with config related changes as part of [MM-52924](https://mattermost.atlassian.net/browse/MM-52924) and noticed that if the config section is removed the settings page would go blank.
https://mattermost.atlassian.net/browse/MM-52977

[MM-52977] Fix potential typeerror if config section is missing

---

plugin.json

7.7 support just ended last month. Going forward it would be good to keep the current ESR as our target minimum version unless strictly necessary to make an emergency bump.

Bump minimum supported server version to current ESR

---

webapp/src/actions.ts

We had this strange issue where profiles would get emptied out almost randomly when loading the Calls expanded view:
Today I was finally able to hunt this down to the `prefetchThread` action that internally calls `getThread`:
```js
getThread(userId: string, teamId: string, threadId: string, extended = true)
```
We were setting the last parameter (`extended`) based on whether CRT was enabled or not. This had the unfortunate effect of causing an almost empty profile to get loaded into the state. It's still unclear why we'd ever want to do that but hopefully someone from webapp can answer that.
@calebroseland Adding you as a sanity check since you originally added this code and if you have any additional thoughts on the above.
https://mattermost.atlassian.net/browse/MM-53508

[MM-53508] Fix potentially empty profiles in expanded view

---

webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/component.tsx
webapp/src/components/incoming_calls/call_incoming_condensed.tsx
webapp/src/components/incoming_calls/expanded_call_container.tsx
webapp/src/components/incoming_calls/hooks.ts
webapp/src/components/switch_call_modal/component.tsx
webapp/src/components/switch_call_modal/index.ts
webapp/src/utils.ts

- Expanded view notifications
- I tweaked the css on the condensed notification (the one that appears above the global widget and above the first notification on the LHS of the webapp and desktop) to be closer to the designs (slightly larger icons, better spacing -- but the spacing on the lhs of the notification, around the avatar and lhs of the message, is a little different than the designs -- those I think are the tweaks Matt made in an earlier PR so I didn't adjust those):
- And here is the expanded view notification:
A couple notes:
- Clicking join on the webapp brings up the switch call modal within the expanded view, and if you press leave&join then the expanded view is closed and you join the new call. Clicking join on the desktop focuses the switch call modal within the desktop's …

MM-53261 - Expanded view notifications

---

Makefile

I'd like to be able to build the plugin on a CI pipeline for testing purposes and don't want to waste resources compiling for all architectures.

Allow compiling single build in CI

---

webapp/src/index.tsx

- This fixes the first load problems we've had.
- Repro steps:
- User A starts a DM call with User B (not logged in), User B logs in
- Expected: User B should see the call icon in the DM channel and should get the incoming call notification with ringing
- Actual (pre-PR): User B does not see the call icon in the DM channel, does not get the incoming call notification. User B will have to click on the DM channel itself to get the call icon in the LHS. They will not receive the call notification at all.
- https://mattermost.atlassian.net/browse/MM-53512

MM-53512 - Fix first load problems

---

webapp/src/actions.ts
webapp/src/components/incoming_calls/call_incoming_condensed.tsx
webapp/src/components/incoming_calls/hooks.ts
webapp/src/types/telemetry.ts

- Adds the following three events to our telemetry:
- `notification_join`
- `notification_dismiss`
- `notification_click_goto_channel`
- And the `channels` source, which along with the `widget` and `expanded_view` show where the event came from.
- A couple notes for feedback:
- I assumed it doesn't matter if the event from the condensed notification comes from the global widget vs the webapp widget (events for those two sources will have the source set to `widget`).
- Similarly, I assumed it doesn't matter if the LHS notification is a regular vs condensed notification (events for those two components will have the source set to `channels`).
- The expanded view on desktop was mistakenly reporting `clientType` of `web` instead of `desktop`, so telemetry prior to v8.1 & Calls v0.18.0 will be …

MM-53292 - Telemetry for DM/GM ringing notifications

---

webapp/src/reducers.ts

It doesn't look like we were updating the reducer when the user left the call. This should fix the issue. 
There could still be a race between disconnect and reaction events but that's more of an edge case. To cover that we'd have to check whether the user is connected to the call before queuing the reaction but at this time it seems a bit overkill.
https://mattermost.atlassian.net/browse/MM-53205

[MM-53205] Remove reaction(s) from store when sending user leaves call

---

server/channel_state.go
server/plugin.go
server/session.go
server/utils.go

We were already caching some stats for telemetry purposes so extending on those to keep track of all participants which we persist the usual way through post props. 
https://mattermost.atlassian.net/browse/MM-53167

[MM-53167] Persist participants list

---

webapp/src/components/custom_post_types/post_type/component.tsx

PR disables shrinking of the call icon to prevent the stretch effect when the content wraps (e.g. frequent in RHS). Also setting the vertical alignment to be centered.
https://mattermost.atlassian.net/browse/MM-54000

[MM-54000] Fix alignment and stretching of call icon in post component

---

webapp/src/components/call_widget/component.tsx

It's possibly the third time I try to fix this. It's easily reproducible on Community but not on local setup so maybe there's some conflicting definition taking place. Anyhow, forcing a max height on the video player element seems to be enough.
https://mattermost.atlassian.net/browse/MM-54144

[MM-54144] Fix screen thumbnail content overflow

---

server/recording_api.go

PR fixes a potential panic due to accessing a `nil` `recState`. 
https://mattermost.atlassian.net/browse/MM-54157

[MM-54157] Fix potential nil access upon starting a recording

---

webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/recording_info_prompt.tsx
webapp/src/constants.ts

PR fixes an issues that would cause the *Recording has stopped. Processing...* message to appear to a newly changed host regardless of when the recording ended.
~~I am adding a threshold (currently one minute) after which we wouldn't show this. Technically we could just show it to the host at the time of stopping the recording but felt it may be useful to keep it around in case of a sudden host change. Overall though I don't have a strong opinion myself and feel it's more of a UX decision.~~
Regardless of what we do here, at some point (likely as part of host controls) we may want to design a message to inform a user that they became the host.
/cc @matthewbirtch in case you'd like to chime in on any of the above.
https://mattermost.atlassian.net/browse/MM-53988

[MM-53988] Improve logic for showing recording stopped banner

---

server/rtcd.go
server/session.go
webapp/src/websocket.ts

This was a fun one. A session was stuck in the call state after the client explicitly left the call and the RTC connection was closed, only to reconnect on the ws channel every now and then hours after the fact.
They key issue here was that we were improperly using the state of the WebSocket object field (`callsClient.ws.ws`) as a way to differentiate between an explicit disconnect (e.g. user leaving call) vs an event triggered disconnect (e.g. network issue). Unfortunately the logic didn't account for the potential edge case of an explicit disconnect happening right after a network disconnect.
The sequence of events was roughly the following:
1. A websocket disconnect happens (network/service related).
a. `this.ws` is set to `null` in the `ws.onclose` handler.
b. `close()` gets called …

[MM-53994] Fix potential stuck session due to ws client leak

---

webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/index.ts
webapp/src/selectors.ts
webapp/src/slash_commands.tsx

PR fixes an issue with toggling the recording state (start/stop). The logic was a bit overly complex which resulted in a bug preventing a host from stopping a recording if this was initializing but not started yet. Slash commands worked better although they were flawed as well (host would be allowed to start a recording while one was initializing, resulting in a server side error).
I am adding a dedicated selector so that we can share the same, simplified logic.
https://mattermost.atlassian.net/browse/MM-53986

[MM-53986] Fix logic to toggle recordings

---

standalone/src/init.ts
standalone/src/recording/index.tsx

A change in https://github.com/mattermost/mattermost-plugin-calls/pull/489 caused the standalone client to fail to connect when starting a call. We move the check into the logic dedicated to the recording client which can make the assumption of always joining an existing/ongoing call.
This problem was caught by e2e tests but unfortunately they are failing to update their status to Github due to an internal security issue which is being worked on (see https://community.mattermost.com/private-core/pl/yxta5iem53y1br93ksjdj7tkyh).

Fix initialization for standalone client

---

lt/client.go

I used to constantly patch the local load-test client every time I wanted to test on Community since we cannot use a system admin account there. So I am adding a proper `setup` flag that when set to `false` avoids any sort of setup (e.g. registering users, joining channels) which works well for cases where the needed entities are already in place.

Implement `setup` flag for load-test client

---

server/session.go
server/websocket.go

It looks like Firefox can be spamming a very long list of candidates if running on an instance with many network interfaces and hit the rate limiter which will drop messages, potentially preventing proper connectivity. What's worse, upon first unmute or screen sharing attempt it will do more of the same.
Note to self: this should be the last time we bump this. If the problem reappears we need to investigate a different solution.
https://mattermost.atlassian.net/browse/MM-54216

[MM-54216] Bump ws rate limiting burst

---

webapp/src/components/call_widget/component.tsx
webapp/src/components/expanded_view/recording_info_prompt.tsx

The condition to show the error was actually inverted, causing the banner to get stuck indefinitely in case of error.
Note: we should likely review this logic and at least have it in a single place, although I don't know how much can be simplified.

Fix recording error logic

---

standalone/src/init.ts
standalone/src/recording/index.tsx
webapp/src/utils.test.ts
webapp/src/utils.ts

PR adds some basic re-try logic to asynchronous requests that could fail due to intermittent networking issues. We implement a simple incremental back off algorithm with a configurable maximum number of attempts and retry interval.
Hopefully this will be enough to overcome the existing issues but will need to be verified on Community prior to merging.
https://mattermost.atlassian.net/browse/MM-54192

[MM-54192] Implement re-try logic for recording client

---

go.mod
go.sum
server/performance/metrics.go
server/websocket.go

PR reviews metrics not to include the call ID + updates the rtcd dependency to port the related fix in https://github.com/mattermost/rtcd/pull/120
Merging into the `release-0.19` branch to allow for a v0.19.1 dot release.
https://mattermost.atlassian.net/browse/MM-54445

[MM-54445] Review metrics

---

e2e/tests/join_call.spec.ts
e2e/utils.ts
webapp/src/reducers.ts

We are still using `voiceConnectedProfiles` on webapp so we need to continue supporting it at least until we bump minimum server version.
https://github.com/mattermost/mattermost/pull/24544
https://mattermost.atlassian.net/browse/MM-54494

[MM-54494] Keep backwards compatibility with older MM versions

---

server/channel_state.go
server/plugin.go

We log the error but otherwise proceed with cleaning up the state.
```
{"timestamp":"2023-09-25 09:12:36.362 -06:00","level":"error","msg":"failed to update call post","caller":"app/plugin_api.go:976","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).cleanCallState channel_state.go:317","err":"GetSinglePost: Unable to get the post."}
```
https://mattermost.atlassian.net/browse/MM-54520

[MM-54520] Soft fail in case of missing post during state cleanup

---

server/utils.go

We had a report of failures to join calls starting in v0.19. At first it looked like a networking issue but upon further inspection of the logs we were able to find multiple plugin crashes due to SIGSEGV. 
Even if properly set to `false` in `config.json` the returned object was a nil pointer. Adding a couple of extra checks to avoid future regressions.
Given the severity of this I'd like to cut a new dot release once this is merged.
https://mattermost.atlassian.net/browse/MM-54551

[MM-54551] Fix potential nil dereference panic

---

.github/workflows/cd.yml

- cd builds are failing, hopefully this is all that's needed.
- none

Add go version to cd

---

go.mod
go.sum
plugin.json
server/bot_api.go
server/public/go.mod
server/public/job.go
server/session.go

PR adds a new bot API endpoint to explicitly report job statuses (e.g. failure, started).
Of **note**, we are now publishing a `github.com/mattermost/mattermost-plugin-calls/server/public` Go module with shared types. I'll slowly start to port over some common structures as needed (e.g. some of those defined in https://github.com/mattermost/rtcd/pull/115). This is still subject to breaking changes and should only be used internally for the time being.
https://github.com/mattermost/calls-recorder/pull/46
https://mattermost.atlassian.net/browse/MM-54589

[MM-54589] Implement job status API

---

go.mod
go.sum

Downstream https://github.com/mattermost/rtcd/pull/121 to fix the broken CI on `go1.21`.
https://github.com/mattermost/actions/pull/13

Fix build on go1.21

---

Makefile
e2e/tsconfig.json
e2e/types.ts

- tsconfig/eslint doesn't play nice if you try to include parent or sibling directories, so let's just include the little bit that I was referencing (like we do for other types in the e2e test project).
- also added the e2e linting to the overall checks... Not sure if you want that, but would have prevented this, so I think it's probably a good thing.
- none

Fix e2e lint issue

---

server/api.go
server/log.go

We add a recover function to catch panics at the API level. 
- A panic at this level won't cause the plugin to crash and potentially kill all running calls in the process.
- We get to log the stack trace at the error level and cleaned up correctly.
Example output:
```
{"timestamp":"2023-10-06 12:22:22.474 -06:00","level":"error","msg":"panic: runtime error: invalid memory address or nil pointer dereference","caller":"app/plugin_api.go:984","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).logPanic log.go:22"}
{"timestamp":"2023-10-06 12:22:22.474 -06:00","level":"error","msg":"goroutine 84 [running]:","caller":"app/plugin_api.go:984","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).logPanic log.go:25"}
{"timestamp":"2023-10-06 12:22:22.474 …
```

[MM-54562] Add panic recover to API handler

---

webapp/src/components/call_widget/component.tsx
webapp/src/index.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts

As part of multi-session support I removed a reducer handler which I forgot to replace properly. That is to handle the client state of the Desktop (webapp) side when we have the global widget. We now need to send the session ID to be able to match properly but other than that it's not too different from before. See [here](https://github.com/mattermost/mattermost-plugin-calls/blob/d834de28e4ec89d6f151dccc0f762dfbcdb75a62/webapp/src/reducers.ts#L219-L223) the previous handler, before removal.

Fix client state on Desktop

---

webapp/src/components/expanded_view/reaction_button.tsx

Nothing fancy, just regulating the `z-index`.
Before:
After:
https://mattermost.atlassian.net/browse/MM-55245

[MM-55245] Move reaction picker on top of reaction stream

---

webapp/i18n/en.json
webapp/src/components/custom_post_types/post_type_recording.tsx
webapp/src/components/icons/ai.tsx

Adds a create summary button when the AI plugin is available. 
The button offloads the logic of what to do afterwards to the AI plugin.
Note that the button positioning varies from the designs because we don't support buttons below the attachments.
Designs: https://mattermost.atlassian.net/wiki/spaces/WD/pages/2510323713/UX+Documentation+for+v1.0#Summarize-Calls-plugin-recordings

Add create summary button.

---

server/configuration.go

I am not sure (which slightly worries me) why we didn't handle these. I want to think it was a simple oversight on my part. Still, they require MM >= 8.0 to show so they wouldn't have helped with the recent customer issue.
https://mattermost.atlassian.net/browse/MM-55617

[MM-55617] Surface config serialization errors

---

webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/components/custom_post_types/post_type/index.ts
webapp/src/constants.ts

- Had to do some trickery to force the display to wrap (because we don't control our custom post's container).
- Doesn't affect non-compact mode, or when a call title is present. If you can think of any other situations I didn't think, please let me know.
| compact, full width | compact, reduced width |
|--|--|
| <img width="1006" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/46ac1efc-cf12-4b39-bae2-73f2674eddc8"> | <img width="544" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/c11090b2-3fb1-4106-ad52-f7d8ccbeb84c"> |
- https://mattermost.atlassian.net/browse/MM-54743

MM-54743 - Fix: In compact mode, the call card displays inline

---

server/bot_api.go
server/job_metadata.go
webapp/src/components/recordings_file_preview.tsx

Adding some logic to save the VTT captions file id into the recording post props so it can be access directly.
I am keeping everything else the same in the call post props even if slightly redundant as this "centralized" data may still be useful if we ever want to retroactively populate calls info whenever we migrate to a proper SQL schema.

Set a captions_file_id post prop to avoid indirection when fetching captions file for video preview

---

go.mod
go.sum
server/bot_api.go
server/job_metadata.go
server/plugin.go
server/store.go

We need to take some extra measures to avoid concurrently reading/writing the call post or we can get into an inconsistent state. This is done at two levels:
- Using the global lock on call to synchronize read/writes for a given call post.
- Implementing a dedicated `GetPost` store method that can fetch from the writer db node since `p.GetPost` can suffer from replica lag.
https://mattermost.atlassian.net/browse/MM-56054

[MM-56054] Fix potential races when accessing or updating call post

---

e2e/tests/popout.spec.ts
webapp/src/slash_commands.tsx

When working on this ticket I realized the `/call leave` command wasn't working due to using `window.callsClient` instead of `window.opener.callsClient`. 
https://mattermost.atlassian.net/browse/MM-55526

[MM-55526] Fix /call leave command from thread

---

e2e/tests/recordings.spec.ts
server/bot_api.go
server/public/job.go
server/public/job_test.go
standalone/package-lock.json
standalone/package.json
webapp/package-lock.json
webapp/package.json
webapp/src/components/recordings_file_preview.tsx

Adding multi language support to generated captions. The client should now expect a `captions: Caption[]` field in the recording post props. Tested this in three languages (english, spanish, italian) :)
https://mattermost.atlassian.net/browse/MM-56089

[MM-56089] Multi language support for captions

---

server/store.go

Looks like MySQL needs a special no-op mapper function in order to correctly translate columns into struct fields.
I wish we could add a test for this but we need some work to make proper integrations tests that run against both db engines. I'll take care of it though. 
For now I manually tested this on both db drivers and it's looking good.
https://mattermost.atlassian.net/browse/MM-56178

[MM-56178] Fix failure to update call post (MySQL)

---

Makefile
build/manifest/main.go
plugin.json

The plugin.json manifest has been "lying", in that it lists support for MacOS (`darwin`) even though we don't support or distribute that. It's necessary to allow developers to work locally.
Fix this by detecting if `MM_SERVICESETTINGS_ENABLEDEVELOPER` is set as truthy in the environment, and dynamically rewriting the manifest to clear the `Executables` and instead the platform-agnostic `Executable`. The server won't know what platform is supported, but will assume it's the right one and "just run it", working fine in development while leaving CI and production builds unchanged.
Then unlist darwin from the canonical manifest.
This complements https://github.com/mattermost/matterbuild/pull/97.
None.

drop darwin from official manifest, build local platform for devs

---

standalone/src/init.ts
webapp/src/browser_routing.ts
webapp/src/index.tsx
webapp/src/selectors.ts
webapp/src/slash_commands.tsx
webapp/src/types/mattermost-webapp/index.d.ts
webapp/src/utils.test.ts
webapp/src/utils.ts
webapp/src/webapp_globals.ts

PR adds some try/catch when accessing properties on the global `window` object to avoid failing with an uncaught error in the unlikely case the object not being accessible/defined (e.g. cross-origin like the bug report).
While reproducing this issue, I realized that the `channelIDForCurrentCall` selector was getting called hundreds of times on channel load. We are now using `createSelector` which should cache the result which seems to be drastically reducing the number of calls. Please let me know if it makes sense.
**Before**
**After:**
https://mattermost.atlassian.net/browse/MM-56048

[MM-56048] Make access to global window properties safer

---

server/websocket.go
server/websocket_test.go

PR implements a session validation check to forcefully disconnect any calls client that has either their session revoked or expired.
https://mattermost.atlassian.net/browse/MM-54359

[MM-54359] Implement session validation check

---

standalone/webpack.config.js
webapp/webpack.config.js

Working process is as follows:
1. Run `npm link` in your local `calls-common` repo directory.
2. Run `npm link @calls/common` in both `mattermost-plugins-calls/webapp` and `mattermost-plugin-calls/standalone`.
3. Build plugin as normal

Fix `npm link` for `@calls/common`

---

go.mod
go.sum
plugin.json
server/activate.go
server/configuration.go
server/configuration_test.go
webapp/src/components/admin_console_settings/ice_host_port_override.tsx
webapp/src/index.tsx

PR adds a new `ICEHostPortOverride` config setting. More context in the linked PR.
https://github.com/mattermost/rtcd/pull/129
https://mattermost.atlassian.net/browse/MM-46676

[MM-46676] Implement config option to override ICE candidates port

---

webapp/src/index.tsx
webapp/src/types/mattermost-webapp/index.d.ts

Discovered during https://github.com/mattermost/mattermost/pull/25889, `registerFilePreviewComponent` may not receive a post. Normally attachments are always associated with posts, but bookmark files don't have an associated post. 
Updating type and adding `?.` to account for this. https://github.com/mattermost/mattermost/pull/25889 contains a backwards-compat. fix to provide an empty object.
https://mattermost.atlassian.net/browse/MM-56718

MM-56718: Conditionally access post

---

server/audit.go

Fixing the response handler in case of `http.StatusNoContent` which we support as part of the resumable upload handler for recordings. Without this we'd get an annoying `http: request method or response status code does not allow body` error logged.
https://mattermost.atlassian.net/browse/MM-48545

[MM-48545] Fix response in case of resumable upload

---

webapp/i18n/en.json
webapp/src/components/channel_header_button/component.tsx
webapp/src/components/channel_header_button/index.ts

We add a case to prevent users from starting a call in a DM with a deactivated user. This is purely a client-side check given a deactivated user wouldn't be able to connect so no need for special handling on the server side.
https://mattermost.atlassian.net/browse/MM-54360

[MM-54360] Don't allow starting calls with deactivated user

---

server/bot_api.go
server/store.go

Since https://github.com/mattermost/mattermost/pull/26239 permissions checks on files require a channel ID to be set so it's not sufficient to use the post ID.

Fix fetching captions

---

webapp/src/components/channel_header_button/component.tsx
webapp/src/components/channel_header_dropdown_button/component.tsx

Changes the icon on the call button to be the filled phone icon instead of the outlined phone icon.
Fixes https://mattermost.atlassian.net/browse/MM-57102
| Before | After |
| --- | --- |
| <img width="103" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/2040554/60f0ebc9-933f-40ec-868f-2eae0bbb14d1"> | <img width="94" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/2040554/5eea6abe-adcb-46d3-bdc7-cf7f4c4e9db3"> |

MM-57102 Update phone icon on channel header call button

---

webapp/src/utils.ts

After some discussion https://community.mattermost.com/core/pl/b8cans4gy7b6fyw9jkstyfp7wr we re-map certain codes to the language files we provide instead of duplicating them.
Fixes https://github.com/mattermost/mattermost-plugin-calls/issues/651

Fix Chinese language code mapping

---

plugin.json

- https://github.com/mattermost/mattermost/pull/24731 has a breaking change, and the earliest server branch with that PR is 9.2.0, so make 9.2.0 our new min server version.
- https://mattermost.atlassian.net/browse/MM-56659

[MM-51852] Update server version to min version that has MM-51852

---

go.mod
go.sum
server/job_metadata.go
server/recording_api.go
server/transcription_api.go

In case of multiple transcription jobs per call we were not writing the metadata correctly which would cause failure to attach and render the captions. 
https://mattermost.atlassian.net/browse/MM-57211

[MM-57211] Fix issues with multiple transcription jobs per call

---

standalone/src/init.ts

The default client used by redux action wasn't accounting for the `basename` any longer so it would break any use of Calls from desktop against installations served under a subpath. Explicitly setting the url seems to fix this.
I think this may be a regression introduced in https://github.com/mattermost/mattermost-plugin-calls/pull/555/files#diff-2aac6bf65edf6e3c7580f45c0aee032bcdded5c0adb7a5ef9929ee31b74e0ad3. 
@cpoile Please let me know if you think this should be addressed differently. It doesn't look great but at the same time I didn't want to go as far as implementing our own basic actions to load MM data in Redux.
Fixes #660 
https://mattermost.atlassian.net/browse/MM-57327

[MM-57327] Set basename on default client as well if present

---

server/db/call_session.go
server/db/call_session_test.go
server/db/call_store_test.go
server/db/migrate_test.go
server/db/migrations/migrations.list
server/db/migrations/mysql/000001_create_calls_channels.up.sql
server/db/migrations/mysql/000003_create_calls_sessions.down.sql
server/db/migrations/mysql/000003_create_calls_sessions.up.sql
server/db/migrations/postgres/000003_create_calls_sessions.down.sql
server/db/migrations/postgres/000003_create_calls_sessions.up.sql
server/db/opts.go
server/public/adapters.go
server/public/call.go
server/public/call_session.go

This is the last bit in terms of new tables (for now). 
As discussed, I am leaving jobs stuff behind for the time being while we figure out if we need them or if we can still rely on post props.
I'll also need to likely tweak some things such as adding indexes but I prefer to defer that to the upcoming PR which will be updating the business logic as it will become clearer how and when we fetch data.
https://mattermost.atlassian.net/browse/MM-42464
https://github.com/mattermost/mattermost-plugin-calls/pull/647

[MM-42464] SQL store: `calls_sessions`

---

go.mod
go.sum
server/job_service.go

Now that we decoupled `calls-offloader` from the job configs we should validate them before creating a job since they'd be simply passed through.
https://github.com/mattermost/calls-offloader/pull/55
https://mattermost.atlassian.net/browse/MM-57483

[MM-57483] Add job config validation

---

e2e/config.ts
e2e/tests/recordings.spec.ts

- e2e tests for live captions off + on
- https://mattermost.atlassian.net/browse/MM-57421

[MM-57421] Live captions e2e tests

---

e2e/tests/popout.spec.ts
webapp/src/components/expanded_view/reaction_button.tsx

PR implements some UX improvements to how the reaction bar and picker behave. We now close them automatically in all of the following cases:
- User reacts
- User presses ESC key
- User clicks outside the element
@matthewbirtch I left raising hand out of this logic since it wasn't specified but let me know.
https://mattermost.atlassian.net/browse/MM-57264

[MM-57264] Close emoji picker and bar when a reaction is chosen

---

webapp/src/components/call_widget/component.scss
webapp/src/components/call_widget/component.tsx

PR improves the calls widget screen sharing preview.
@matthewbirtch I took a chance to also update the button to follow the color and hover/active states. Let me know if that wasn't expected.
*Before*
*After*
https://mattermost.atlassian.net/browse/MM-57290

[MM-57290] Calls widget: improve screen sharing preview UX

---

plugin.json

Fix invalid manifest type

---

server/client_message.go
server/websocket.go
server/websocket_test.go
webapp/src/components/expanded_view/component.tsx
webapp/src/index.tsx
webapp/src/utils.ts

PR should fix most of the remaining call state data races originally mentioned in https://github.com/mattermost/mattermost-plugin-calls/pull/512, specifically when loading the pop out window and in case of a websocket reconnect.
This is done by implementing a websocket request handler that returns the calls state under lock. Using the websocket channel as opposed to making HTTP request should guarantee a valid sequencing of potentially concurrent events (e.g. users joining, leaving, etc).
https://mattermost.atlassian.net/browse/MM-57737

[MM-57737] Improve client side call state consistency

---

webapp/src/components/expanded_view/component.tsx

Unfortunately in https://github.com/mattermost/mattermost-plugin-calls/pull/681 we traded a race for another one. The ws client may still be initializing when the popout opens which would make our request a no-op and the state would be permanently missing as a consequence. We add a check for that.

Fix fetching call state in popout

---

server/db/calls_channels_store.go
server/db/calls_channels_store_test.go
server/db/calls_jobs_store.go
server/db/calls_jobs_store_test.go
server/db/calls_sessions_store.go
server/db/calls_sessions_store_test.go
server/db/calls_store.go
server/db/calls_store_test.go

Relying on [`RowsAffected()`](https://pkg.go.dev/database/sql#Result) is just not going to work. Making the operations idempotent so that it doesn't matter if the state is the same. We can look into some optimizations later on.

Make update and delete store operations idempotent

---

server/api_router.go
server/host_controls.go
server/host_controls_api.go
server/websocket.go
standalone/src/init.ts
standalone/src/recording/components/recording_view/index.tsx
webapp/i18n/en.json
webapp/src/actions.ts
webapp/src/components/call_widget/participant.tsx
webapp/src/components/expanded_view/call_participant.tsx
webapp/src/components/expanded_view/call_participant_rhs.tsx
webapp/src/components/expanded_view/component.tsx
webapp/src/components/host_controls_menu.tsx
webapp/src/index.tsx
webapp/src/websocket_handlers.ts

- Implements the mute participant host control
- Pretty straightforward, doesn't show if yourself or if the participant is muted already.
- https://mattermost.atlassian.net/browse/MM-57907

[MM-57907] Mute participant

---

e2e/tests/popout.spec.ts
e2e/types.ts
webapp/src/index.tsx

- The `websocket reconnect handler` was causing the state to be reset every minute or so when the window is in the background. So if you're on a call and you put the expanded view in the background, it would be blank when you come back after a reset.
- https://mattermost.atlassian.net/browse/MM-57965

[MM-57965] fix Websocket reconnect handler

---

.github/workflows/e2e.yml

Just noticed we were not running these on merging to `main`. I think we should, and on tags (releases) as well.

Run e2e tests on tags and main branch

---

webapp/src/index.tsx

PR fixes some other issues with fetching assets when MM is running under a subpath. It's the same fix as https://github.com/mattermost/mattermost-plugin-calls/pull/663 but ported to the webapp side.
I am not sure what happened here since you raised this exact point in https://github.com/mattermost/mattermost-plugin-calls/pull/663#pullrequestreview-1946394499 which I thought I addressed as there was no harm in doing it on both sides but in the end I obviously didn't :man_facepalming: 
Fixes https://github.com/mattermost/mattermost-plugin-calls/issues/722
https://mattermost.atlassian.net/browse/MM-58125

[MM-58125] Fix Client4 initiated requests when running under subpath

---

go.mod
go.sum
lt/go.mod
lt/go.sum
server/activate.go

Bumping `rtcd` to the latest release.

Bump rtcd to latest v0.15.0

---

e2e/tests/notifications.spec.ts
webapp/src/components/incoming_calls/call_incoming_condensed.tsx

- Removed the check for expanded view (not sure why we even had that -- the channel switch does work in safari.
- https://mattermost.atlassian.net/browse/MM-58033

[MM-58033] Fix: Incoming call banner in expanded view not working

---

webapp/src/components/expanded_view/component.tsx

A small UX regression due to the sizing changes in https://github.com/mattermost/mattermost-plugin-calls/pull/715 which we weren't accounting for in case of screen sharing.
*Before*
*After*

Fix pop out height

---

.github/workflows/e2e.yml
.github/workflows/generate-e2e-report.yml

- Generate pending status check before the report generation in order to avoid a false positive success from the E2E tests execution
- Remove the pull request condition in order to run also on master
https://mattermost.atlassian.net/browse/CLD-7757

fix: Generate status check before the report generation

---

webapp/src/reducers.ts

- Fixing how we handle call_end, which left the desktop thinking we were still in a call:
- https://mattermost.atlassian.net/browse/MM-58544

[MM-58544] Fix call_end for desktop

---

go.mod
go.sum
server/plugin.go
server/websocket.go

PR improves logging of which sessions join calls, including all the most important IDs.
Example:
```
{"timestamp":"2024-06-05 06:44:32.750 -06:00","level":"info","msg":"session has joined call","caller":"app/plugin_api.go:1008","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin.func1 websocket.go:745","userID":"zjm6x7y4n3gjzfj7kw3xp9c9se","sessionID":"5dbfn67ubtr3fkhqb9octcu5iy","channelID":"oi18bftr738ntn35xnyjyed9uh","callID":"g3y3k1to57y85puaccnwgj7ber"}
```
https://mattermost.atlassian.net/browse/MM-45236

[MM-45236] Improve auditing of joining sessions

---

e2e/tests/popout.spec.ts
webapp/src/components/expanded_view/component.tsx
webapp/src/components/reaction_stream/reaction_stream.tsx

PR fixes an issue with the call thread rendering on top of the call view, causing some buttons on the right side (e.g. leave call) to be hidden in some instances.
I had to wrestle with CSS to make sure I didn't break previously fixed things, namely:
- Call settings menus rendering on top of the call thread in case of overlap.
- Reactions rendering on top of calls view.
- Call view rendering on top of the annoying onboarding button.
Please give it a try and let me now if anything unexpected broken due to this.
https://mattermost.atlassian.net/browse/MM-58285

[MM-58285] Fix expanding call thread

---

webapp/src/components/channel_link_label/component.tsx

PR fixes some outstanding issues with the rendering of the active call icon in the sidebar. This requires some webapp changes to work in all cases (see related PR).
https://www.figma.com/design/KAdDampXIcjzQ8oWMs7LpZ/MM-53491-Calls%3A-Rendering-of-LHS-active-call-icon?node-id=1-7&m=dev
https://mattermost.atlassian.net/browse/MM-53491
https://github.com/mattermost/mattermost/pull/27172

[MM-53491] Fix rendering of active call icon in sidebar's channel link

---

Makefile
plugin.json

- We made a little mistake in bundling. Instead of splitting the files (png staying in the server pkg so we can embed it, and svg moving to the `/assets` dir) to conform to the makefile, just changed the makefile's asset directory var. Also need to change the `plugin.json` location.
- Will need to cut `v0.28.1` after. I did not delete the `v0.28.0`, but I wanted to just to get the automatic comment. :)
- none

Fix asset bundling

---

e2e/page.ts
e2e/tests/notifications.spec.ts
webapp/src/actions.ts

- Actual broken test, bisected the problem to a change in how mattermost mounts react components: https://github.com/mattermost/mattermost/pull/27192
- Looks like the e2e test wasn't detecting a real break, I think it just runs too quickly. So: 1) ensuring that patching is applied by reloading after (kind of unrelated to the above PR but might have been contributing to flakiness in the past), and 2) adding a timeout of 0 to flush the event loop of the page (allowing react to fully load), and that fixes it.
- https://mattermost.atlassian.net/browse/MM-58773

[MM-58773] Fix broken notifications test

---

webapp/i18n/en.json
webapp/src/components/expanded_view/component.tsx
webapp/src/components/expanded_view/controls_button.tsx

A minor improvement to the unmute button on the expanded view to include info about the space bar trigger. 
https://mattermost.atlassian.net/browse/MM-58293

[MM-58293] Add subtext on unmute tooltip

---

e2e/tests/notifications.spec.ts
webapp/src/actions.ts
webapp/src/reducers.ts
webapp/src/websocket_handlers.ts

- When refactoring `CALL_END` I tried to make it do too much (it removed the incoming notification, but that hid that we weren't also removing the ringing). Also, `CALL_END` was being sent in a couple places. 
- Consolidated the call end logic to one function, and it is its job to do all the call cleanup.
- https://mattermost.atlassian.net/browse/MM-59027

[MM-59027] Fix: Ringing not stopping after leave or /call end

---

.github/workflows/e2e.yml

We do not need to trigger the e2e report summary status check . 
We can post it after the report is generated
Fixes: https://github.com/mattermost/mattermost-plugin-calls/pull/794#issuecomment-2186422441

fix: Remove status check posting from e2e tests

---

.github/workflows/generate-e2e-report.yml

Send a success status on e2e tests no matter failures. Let the reviewer judge if it's flaky tests or not while not blocking the merge

fix: Always send a success status check when e2e tests are done

---

webapp/src/components/call_widget/component.tsx

Removing the subtext as a quick fix to avoid it from getting cut off.
https://mattermost.atlassian.net/browse/MM-53062

[MM-53062] Fix screensharing permissions message tooltip cut off on Desktop

---

server/db/calls_sessions_store.go
server/db/calls_sessions_store_test.go
server/push_notifications.go
server/push_notifications_test.go

PR adds some logic to suppress mobile push notifications for replies to a call thread if the receiver is in that call. This is to mimic (see note) the behavior of the web/desktop [client-side hook](https://github.com/mattermost/mattermost-plugin-calls/blob/29644adc8548c9fabccd37706209f54565547a81/webapp/src/desktop_notifications.ts#L14).
Note: I haven't found an easy way to check for mentions, so we'd be disabling any type of notification, which I find reasonable for the call thread, given the user should have the app open somewhere.
https://mattermost.atlassian.net/browse/MM-58292

[MM-58292] Suppress push notifications to call thread if receiver is in call

---

server/public/job.go
server/websocket.go

While working on https://github.com/mattermost/calls-transcriber/pull/27, I realized that any connected client could craft a WebSocket message to display arbitrary captions from any other user connected to the call. 
The UserID field was also redundant since we can easily find that information from the call session object.
https://mattermost.atlassian.net/browse/MM-59072

[MM-59072] Don't require user ID in caption message

---

.github/workflows/e2e.yml
go.mod
go.sum
plugin.json

Last PR needed before cutting v0.29

Update recorder and transcriber

---

go.mod
go.sum

Updating the `rtcd` dependency to fix a regression. See https://github.com/mattermost/rtcd/pull/151.
I'll update the base branch as soon as we have a proper one.
https://mattermost.atlassian.net/browse/MM-59548

[MM-59548] Update rtcd

---

lt/client/client.go
lt/cmd/speech/main.go

PR removes the CGO dependency from our main load-test command (i.e. `./lt/cmd/lt`) since it has caused a bit of pain for our customers as it requires some extra system dependencies which are not always straightforward to install. Given the opus encoder is only used by the `speech` command, we can extract it over there through the use of a common interface.

Remove CGO dependency for load-test main binary

---

server/db/stats_store.go
server/db/utils.go
server/db/utils_test.go

Working with time is hard enough. Working with dates is just brutal.
PR tries to fix some flakiness caught in CI tests on this day (Jul 30th). The way `time.AddDate` works made it possible to get duplicate months due to normalization. Now we are ensuring to always use the first day of the month rather than the current one which should guarantee no duplicates are added (added a test).

Fix dates flakiness in calls stats

---

.github/workflows/e2e.yml

Fixes:
```
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Error: Process completed with exit code 18.
```
Context: https://hub.mattermost.com/private-core/pl/8fm5sw499bnbpmnnrgrg4smfno 
https://mattermost.atlassian.net/browse/CLD-8201

[fix] CI - e2e workflow auth against dockerhub

---

.github/workflows/e2e.yml

Conditionally authenticating against dockerhub to remove pull limits, only if not running in a forked PR.
Rationale: https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
https://mattermost.atlassian.net/browse/CLD-8203

[fix] ci in forks, do not auth againstn dockerhub

---

README.md

This PR adds the language (`bash`) to the README code blocks, and removes the extra backticks from one of them.

fix README code blocks

---

standalone/src/init.ts
webapp/src/action_types.ts
webapp/src/actions.ts
webapp/src/index.tsx
webapp/src/reducers.ts

Found an interesting edge case when testing the new recorder image. If a user is connected more than once to the same call (multi sessions), then any of their sessions leaving would cause the recording state to be reset for all of them.
I tried to fix this in a couple of different ways (i.e., persisting the previous call sessionID or just avoiding clearing the state), but they all come with some tradeoffs, so I eventually decided that having a more explicit redux action to track the local client closing may be the cleanest option.
https://mattermost.atlassian.net/browse/MM-60010

[MM-60010] Fix recording state cleared when session for same participant leaves

---

e2e/tests/media.spec.ts

AV1 test has been a bit flaky, timing out during cleanup.

Bump e2e timeout

---

.github/workflows/e2e.yml
go.mod
go.sum
lt/go.mod
lt/go.sum
plugin.json

We are making MM v10 a requirement for running Calls v1 since it makes it more explicit we are introducing breaking changes (namely Calls being available only in DMs for unlicensed servers).
Also bumping some Calls dependencies in the process as we are wrapping up the release.

Calls v1 prep

---

.github/workflows/generate-e2e-report.yml

This PR utilizes the `main` branch version of the repository when producing the E2E test report.
The ref to check out doesn't need to be specified, because for `workflow_run` it's the default branch out-of-the-box:
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run
- https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4

Utilize reporting script from default branch

---

server/batching/batcher.go
server/session.go
server/websocket.go
server/websocket_test.go

When working on unrelated `rtcd` changes, I noticed a couple of flaky tests. At times, some sessions would fail to connect due to timeout without a clear explanation.
After a good amount of investigation, I was able to track this down to the batching behaviour not working as expected in case of concurrent join/leave operations on the same channel. In fact, it would be possible to stop batchers that still had some queued items (e.g., sessions trying to join). This resulted in those sessions to timeout as they wouldn't ever be handled.
We fix this by simply checking (under lock) for emptiness before stopping the batches.
Writing a test for this wasn't easy but I managed to reproduce it several times, although it's not 100% consistent due to the specific timings involved. …

[MM-60199] Fix race condition in case of concurrent leave/join in the same channel

---

e2e/playwright.config.ts
e2e/tests/join_call.spec.ts
e2e/tests/media.spec.ts

Some tests are timing out without clear signs of failure other than taking a littler longer to process.

Bump e2e timeouts to address flakyness

---

.github/workflows/e2e.yml
.github/workflows/generate-e2e-report.yml
e2e/config-patch.json
e2e/overlay-config.jq
e2e/scripts/prepare-server.sh
e2e/scripts/run.sh
e2e/tests/desktop.spec.ts
server/slash_command.go
webapp/src/client.ts
webapp/src/constants.ts
webapp/src/log.ts
webapp/src/slash_commands.tsx
webapp/src/utils.ts

Porting changes of https://github.com/mattermost/mattermost-plugin-calls/pull/840 to v0.29. This will be pre-packaged with an upcoming MM v9.11 ESR. 
This will unblock customers running Desktop from sharing debugging information (logs and stats).
/cc @amyblais

[MM-59996] Make stats and client logs more easily accessible

---

e2e/scripts/run.sh

Printing calls-recorder/transcriber logs have been often failing as of late with `Error response from daemon: can not get logs from container which is dead or marked for removal`. 
We only really care about exited containers, which are retained past their execution. Ideally we'd filter by exit code but the `docker ps` filter functionality doesn't seem to support advanced logic such as `exited!=0`.

Fix e2e pipeline flakyness

---

go.mod
go.sum
lt/client/client.go
lt/go.mod
lt/go.sum
server/mocks/github.com/mattermost/rtcd/service/rtc/mock_Metrics.go
standalone/package-lock.json
standalone/package.json
webapp/package-lock.json
webapp/package.json

Not much on this side. Mostly updating dependencies and the load-test client to generate and send client metrics.
https://github.com/mattermost/calls-common/pull/41
https://github.com/mattermost/rtcd/pull/159
https://mattermost.atlassian.net/browse/MM-60561

[MM-60561] RTC client metrics

---

.github/workflows/e2e.yml
go.mod
go.sum
lt/go.mod
lt/go.sum
plugin.json
standalone/package-lock.json
standalone/package.json
webapp/package-lock.json
webapp/package.json
webapp/src/client.ts

Updating the various dependencies. The only significant change here is I am bumping `rtcMonitorInterval` from 4s to 10s as it results in much higher quality stats (less variance) and possibly avoid more false positives with call quality detection.

Prepare v1.2.0 release

---

.github/workflows/e2e.yml
e2e/docker/docker-compose.yaml
e2e/docker/postgres.conf
e2e/scripts/prepare-server.sh

Fixing the e2e pipeline. The only dependency we need is Postgres, so we can spin up that service by ourselves without relying on files from a different repo.
https://mattermost.atlassian.net/browse/MM-61298

[MM-61298] Fix e2e pipeline

---

webapp/i18n/en.json
webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/utils.test.ts
webapp/src/utils.ts

- Surfacing the presence of transcriptions (same as we do for recordings) in call root post.
- Added proper type validation of the job metadata object.
- Remove usage of deprecated `recording_files` prop. The `recordings` object should be used instead.
As a next step, I'll try looking into mobile since we don't have this UX feature on that side at all.
https://mattermost.atlassian.net/browse/MM-61228

[MM-61228] Surface transcriptions in call post

---

.github/workflows/e2e.yml

I think the existing check was overly strict since it's only running on PRs. In fact,  `main` branch is [now failing](https://github.com/mattermost/mattermost-plugin-calls/actions/runs/11331363665/job/31511439495) due to rate limiting.

Fix docker login step

---

webapp/i18n/en.json
webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/utils.test.ts
webapp/src/utils.ts

Since props cannot be trusted (i.e., users can alter them at any time on their posts), we must take extra care to ensure that the type of them is what we expect it to be.
https://mattermost.atlassian.net/browse/MM-61166

[MM-61166] Ensure full validation of Calls post props

---

e2e/tests/start_call.spec.ts

Adding some extra checks so that we could have caught this way sooner.
https://mattermost.atlassian.net/browse/MM-61233

[MM-61233] Verify no error is shown when running slash commands

---

.github/workflows/e2e.yml
e2e/docker/docker-compose.yaml
e2e/docker/postgres.conf
e2e/scripts/prepare-server.sh
e2e/scripts/run.sh
webapp/i18n/en.json
webapp/src/components/custom_post_types/post_type/component.tsx
webapp/src/utils.test.ts
webapp/src/utils.ts

Cherry-pick of 74d6f31 in `release-0.29` to prepare for dot release.
https://mattermost.atlassian.net/browse/MM-61166

[MM-61166] Cherrypick to `release-0.29`

---

.github/workflows/e2e.yml

Fix conditional for not logging into dockerhub when running on forks:
- Explicitly state which repository the E2E test should run for
- Remove quotes around `if` condition
I'll double check that this works and then mark this as ready-for-review

Fix E2E tests for forks

---

e2e/tests/desktop.spec.ts
webapp/src/components/screen_source_modal/component.tsx

We implement a tooltip so that longer source names that it's easy to display the full name in case it gets truncated.
/cc @matthewbirtch 
https://mattermost.atlassian.net/browse/MM-61224

[MM-61224] Add tooltip to screen source names

---

e2e/tests/admin_console.spec.ts
webapp/src/components/admin_console_settings/allow_screen_sharing.tsx

When the setting was missing (e.g. new installation), the admin console UI would incorrectly report it as disabled (false) since it was undefined. This could cause confusion, given the default on the server is true (screen sharing is allowed).
https://mattermost.atlassian.net/browse/MM-61470

[MM-61470] Fix rendering of AllowScreenSharing config setting

---

e2e/package-lock.json
e2e/package.json
e2e/playwright.config.ts
e2e/tests/popout.spec.ts
webapp/src/components/expanded_view/component.tsx

This is most likely a CSS regression in Firefox (the way flexbox behaves with a child with 100% height). I was only able to reproduce on version 139 so far. Chrome works as expected.
That said, even the Chrome rendering wasn't great since it created an extra gap between the actual player content and the wrapper. This feels better now.
I added an e2e test and ran it on Firefox, but it didn't reproduce the issue since Playwright currently ships Firefox 131. Enabling the whole pipeline on Firefox requires far more work (tracking at https://mattermost.atlassian.net/browse/MM-61558).
*Before*
*After*
https://mattermost.atlassian.net/browse/MM-61555

[MM-61555] Fix rendering issue with screen sharing player

---

.github/workflows/e2e.yml
e2e/scripts/prepare-server.sh
plugin.json

Without the AVX512 complicacy, we should now be able to use the official transcriber image in e2e tests.

Bump transcriber

---

webapp/src/components/incoming_calls/call_incoming_condensed.tsx

Fixing a tooltip placement issue that caused it to be out of the bounds of our global widget window.
*Before*
*After*
https://mattermost.atlassian.net/browse/MM-61538

[MM-61538] Fix incoming call banner tooltip placement in global widget

---

go.mod
go.sum
server/activate.go
server/websocket_test.go

Two changes on this side:
- Using the new `UDPSocketsCount` setting to limit the number of listening UDP sockets created by the embedded RTC server. In this mode, scaling isn't a goal, so we reduce them to NumCPU.
- I can't exactly recall what led to the existing activation sequence, but we'd be starting up the embedded RTC server regardless of whether RTCD is used. This seems wrong as it causes us to use unnecessary resources on the Mattermost side (e.g. opening sockets that will never be used).
https://github.com/mattermost/rtcd/pull/162
https://mattermost.atlassian.net/browse/MM-61786

[MM-61786] Reduce number of open file descriptors

---

server/activate.go

Partially cherry-picking https://github.com/mattermost/mattermost-plugin-calls/pull/908 to include in a dot release (v0.29.5) since it was a bug to initialize the embedded RTC server when rtcd is in use.

Don't initialize RTC server when using external rtcd service

---

server/activate.go

This is slightly embarrassing. I introduced a regression in https://github.com/mattermost/mattermost-plugin-calls/pull/908 because I cannot read my own code. The second statement in that PR (that we'd be starting up the embedded RTC server regardless of whether RTCD is used) is wrong as [there was a `return` statement](https://github.com/mattermost/mattermost-plugin-calls/blob/dbd50f9953281824dd59fcc894d1efde8e4f2689/server/activate.go#L165) in the block so that change wasn't required at all.
And while making that change, I forgot the importance of setting `p.nodeID` , which should only be done when RTCD is not in use. 
Unfortunately, e2e tests couldn't spot this since they run in a non-HA (created https://mattermost.atlassian.net/browse/MM-62065). I ran some basic manual test in HA …

[MM-62064] Leave nodeID empty when using RTCD service

---

server/activate.go

Cherry-picking the fix in https://github.com/mattermost/mattermost-plugin-calls/pull/912 to prepare a v1.3.2 dot release.

Cherrypick MM-62064 v1.3 

---

server/cluster_message.go
server/plugin.go
server/websocket.go

Our new HA-capable e2e tests have surfaced a bug causing signaling issues for sessions reconnecting in a non-RTCD HA deployment.
The optimal path would still be to pull the trigger on https://mattermost.atlassian.net/browse/MM-53376, but we'll have to defer it to the next major version bump (MM v11 / Calls v2).
https://mattermost.atlassian.net/browse/MM-62178

[MM-62178] Fix signaling after WS reconnect in non-RTCD HA

---

.github/workflows/e2e.yml
e2e/config-patch-core.json
e2e/scripts/merge-reports.js
e2e/scripts/prepare-server.sh
e2e/scripts/run-core.sh
e2e/scripts/run.sh
e2e/tests/join_call.spec.ts
e2e/tests/media.spec.ts
e2e/tests/recordings.spec.ts

PR adds `rtcd` support to our e2e pipeline. The rtcd image is dynamically built from a matching branch name (if it exists) or `master` as fallback. This will help with running the entire pipeline against specific changes on the other side.
I am also tagging a subset of tests to execute in plugin mode (i.e. without rtcd service). These should be fairly quick and will run in addition to the above and help to avoid a potential blind spot.
https://mattermost.atlassian.net/browse/MM-62090

[MM-62090] Include rtcd service in e2e pipeline

---

.github/workflows/e2e.yml
e2e/scripts/prepare-server.sh
e2e/scripts/run.sh

Some minor improvements on how we print and persist logs in our e2e tests.

Improvements to e2e logs

---

.github/workflows/generate-e2e-report.yml

Restore permission to write commit status checks to the E2E reporting workflow.
Example job failure: https://github.com/mattermost/mattermost-plugin-calls/actions/runs/12787003506/job/35645267076#step:7:24

Add commit satus write permission to E2E report

---

.gitignore
server/bot_api.go
server/bot_api_test.go

Fixing a panic that triggered yesterday in our team call (eventually causing a transcription job failure). A user unmuted right when the call was ending, causing the transcriber to fetch the profile of the unmuting user. When the fetch happened the session for the user was gone. This case was handled but it wasn't updated to expect pointers (we used to store values on a previous iteration), causing a nil dereference.
I used Aider to generate some boilerplate test code but eventually had to more or less write all the cases manually.
https://mattermost.atlassian.net/browse/MM-62579

[MM-62579] Fix panic in handleBotGetProfileForSession

---

e2e/tests/popout.spec.ts

The label has changed upstream, causing the e2e test to time out consistently.

Fix failing e2e

---

e2e/docker/docker-compose.yaml
server/testutils/containers.go

Updating the testing pipelines to use the new version.
Relates to https://github.com/mattermost/mattermost/pull/30039

Bump Postgres to v13

---

webapp/package-lock.json

Updating `path-to-regexp` dependency to v1.9.0
https://mattermost.atlassian.net/browse/MM-62884

[MM-62884] Update `path-to-regexp` package to v1.9.0

---

e2e/tests/start_call.spec.ts
webapp/src/client.ts
webapp/src/components/user_settings/audio_devices_settings_section.tsx

I noticed that every time I replug my camera or restart the laptop, my default devices are reset. This is because the device IDs are not consistent across these events. 
What remains stable, though, is the device label, so I am opting to use this instead.
I think there's a small chance we could get more than one device with the same label, so we still support strict ID matching as a fallback in such cases.
https://mattermost.atlassian.net/browse/MM-63274

[MM-63274] Use device label instead of id to save defaults

---

webapp/src/websocket_handlers.ts

Joining from both mobile web today, I realized that on web, you get the "self joined" sound when connecting from mobile, which is weird. We should check against the session ID to be more precise rather than user ID.

Fix self join sound in case of multi sessions

---

server/db/calls_channels_store.go
server/db/calls_channels_store_test.go
server/db/calls_jobs_store.go
server/db/calls_jobs_store_test.go
server/db/calls_sessions_store.go
server/db/calls_sessions_store_test.go
server/db/calls_store.go
server/db/calls_store_test.go
server/db/misc_store.go

When reverting from the video branch, everything broke down. This is because `SELECT *` is not backward compatible in case a new column is added.
Tests were Aider-generated, which I reviewed.
https://mattermost.atlassian.net/browse/MM-63373

[MM-63373] Replace usage of `SELECT *`

---

server/api.go
server/plugin.go
server/public/version.go
server/rtcd.go
standalone/package-lock.json
standalone/package.json
standalone/src/init.ts
webapp/package-lock.json
webapp/package.json
webapp/src/action_types.ts
webapp/src/actions.ts
webapp/src/client.ts
webapp/src/index.tsx
webapp/src/reducers.ts
webapp/src/selectors.ts
webapp/src/types/types.ts

We expose RTCD versioning info on top of the existing plugin version/build pair. We then use this information to detect whether we can safely use the new DC locking functionality.
A test plan for both backward and forward compatibility is attached to the JIRA ticket.
https://mattermost.atlassian.net/browse/MM-63889

[MM-63889] Add backend version check to enable DC locking

---

server/websocket.go
webapp/src/websocket.test.ts
webapp/src/websocket.ts

We received a report of some significant delays in WS disconnect detection on the client side. On the server side, we wait up to 10 seconds for a gone client to reconnect, then give up, closing the underlying peer connection, even if healthy. Adding an explicit ping mechanism should help to mitigate this issue and trigger a reconnect before the server-side timeout expires.
https://mattermost.atlassian.net/browse/MM-64539

[MM-64539] Implement simple ping mechanism in WebSocket client

---

e2e/channels.ts
e2e/config.ts
e2e/global-setup.ts
e2e/scripts/prepare-server.sh
e2e/tests/notifications.spec.ts
e2e/tests/start_call.spec.ts
e2e/users.ts
e2e/utils.ts

We'll soon deprecate cookie-authenticated API requests without a valid CSRF token, which would break the e2e pipeline completely.
https://mattermost.atlassian.net/browse/MM-64237

[MM-64237] e2e: use proper CSRF header in requests

---

e2e/tests/start_call.spec.ts

This has been flaky for a while, getting stuck on pressing `Enter` key. We take a different approach and use the `Save` button instead.

Fix flaky e2e test
