mattermost/mattermost-plugin-calls

server/api.go, webapp/src/components/switch_call_modal/component.scss, webapp/src/components/switch_call_modal/component.tsx, webapp/src/components/switch_call_modal/index.ts, webapp/src/utils.ts
PR fixes a couple of issues with the Switch Call modal which wasn't displaying properly with calls in DMs/GMs due to the missing display name. I also changed the modal's styling to adhere to our product guidelines. Please let me know if I missed anything.
=> Improve switch call modal

.circleci/config.yml
- Fix an annoying little side-effect of how matterbuild works.
- none
=> Fix release process

plugin.json
- Fix plugin.json for the marketplace
- none
=> Fix release process 2

webapp/src/vad.ts
PR tunes VAD to allow for smoother transitions, accounting for small pauses to avoid the flickering.
https://mattermost.atlassian.net/browse/MM-42396
=> [MM-42396] Smoother VAD

server/slash_command.go, webapp/src/index.tsx, webapp/src/utils.ts
PR doesn't add any feature per se but implements some minimal boilerplate to potentially enable new fun and exciting stuff.
https://mattermost.atlassian.net/browse/MM-42549
=> [MM-42549] Implement slash command to turn on/off experimental features

server/api.go
We limit access to the `/debug` endpoint to system admins. Purposely leaving `/metrics` open as it's unlikely to cause performance issues if abused and at the same time it's much easier to hook up in Prometheus.
https://mattermost.atlassian.net/browse/MM-42711
=> [MM-42711] Require authorization to access `/debug` endpoint

go.mod, server/activate.go, server/api.go, server/audit.go, server/log.go, server/plugin.go, server/websocket.go
PR adds some additional logs to HTTP requests requiring authorization.
Example:
```
{"timestamp":"2022-04-29 16:34:02.906 +02:00","level":"info","msg":"handlePostChannel","caller":"app/plugin_api.go:937","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).httpAudit audit.go:21","remoteAddr":"192.168.1.108:37544","method":"POST","url":"/m9xziz1hdjdsmck86b39ye7fqa","header":"map[Accept:[*/*] Content-Length:[16] Content-Type:[application/x-www-form-urlencoded] Mattermost-User-Id:[647qcbo3fib3jm6ehq9tqmuhxc] User-Agent:[curl/7.68.0]]","host":"172.17.0.1:8065","status":"success"}
```
https://mattermost.atlassian.net/browse/MM-43330
=> [MM-43330] Improve logs for auditing

server/session.go
Noticed a couple of dropped candidates in community so bumping the burst rate a bit to allow for clients with plenty of network interfaces.
@cpoile I am happy to cut v0.5.0 after merging this. Let me know what you think.
=> Bump burst rate

webapp/src/components/call_widget/component.tsx
The style was static so switching between teams with different themes wasn't updating it. Added a method to regenerate it upon theme change.
https://mattermost.atlassian.net/browse/MM-43842
=> [MM-43842] Make call widget style react to theme change

go.mod, go.sum, server/activate.go, server/plugin.go, server/utils.go
Companion PR to https://github.com/mattermost/rtcd/pull/27
https://mattermost.atlassian.net/browse/MM-44062
=> [MM-44062] Move STUN logic to rtcd

webapp/.eslintrc.json, webapp/package.json, webapp/src/client.ts, webapp/src/index.tsx, webapp/src/types/types.ts, webapp/src/utils.test.ts, webapp/src/utils.ts, webapp/src/websocket.ts
We should take into account if server's config has `WebsocketURL` set in order to properly ovverride the URL we connect to when starting/joining a call.
Fixes #90 
https://mattermost.atlassian.net/browse/MM-44679
=> [MM-44679] Use config to determine WebSocket URL

webapp/.eslintrc.json, webapp/src/client.ts, webapp/src/components/call_widget/component.tsx, webapp/src/index.tsx, webapp/src/log.ts, webapp/src/utils.ts, webapp/src/vad.ts, webapp/src/websocket.ts
Making client logs a bit more consistent and easier to work with in case of debug.
https://mattermost.atlassian.net/browse/MM-44227
=> [MM-44227] Review client-side logs

Makefile, plugin.json
Fixes #97
https://mattermost.atlassian.net/browse/MM-44893
=> [MM-44893] Add OpenBSD build to Calls plugin release

webapp/src/index.tsx
We were following any thread upon receiving call start event. Added a check to make sure we only follow the call we are currently in.
https://mattermost.atlassian.net/browse/MM-44965
=> [MM-44965] Fix following threads

webapp/src/components/call_widget/component.tsx, webapp/src/index.tsx, webapp/src/utils.ts, webapp/src/websocket.ts
Fixes #112 
https://mattermost.atlassian.net/browse/MM-45155
=> [MM-45155] Add support for using plugin when MM is served under a subpath

server/websocket.go
We were sending the join acknowledge event before initializing the actual call session. This could lead to a potential race condition where client signaling data gets discarded because it's received prior to initializing the rtc session.
PR reworks the ordering slightly to make sure we send the join event after creating the session.
Originally reported in https://github.com/mattermost/mattermost-plugin-calls/issues/134
https://mattermost.atlassian.net/browse/MM-45499
=> [MM-45499] Fix ordering to avoid race condition on session initialization

.gitlab-ci.yml, e2e/global-setup.ts, e2e/playwright.config.ts
Adds `.gitlab-ci.yml` hook to internal definitions and updates setup logic to enforce `defaultenabled` plugin configuration instead of individual enabling for channels.
=> e2e: Gitlab integration

server/api.go
Tiny consistency fix when returning channels.
https://mattermost.atlassian.net/browse/MM-45288
=> [MM-45288] Return empty array instead of null

server/api.go, server/websocket.go
Forgot to track a couple of new events.
=> Track new events

e2e/global-setup.ts
Prevent the [new Desktop App prompt](
https://github.com/mattermost/mattermost-webapp/pull/10653) from interfering in tests.
=> e2e: Disable new landing page for test users

webapp/src/actions.ts
Fixes https://github.com/mattermost/mattermost-plugin-calls/pull/162
=> Fix telemetry prop

webapp/src/components/avatar/avatar.tsx, webapp/src/components/call_widget/component.tsx, webapp/src/components/expanded_view/component.tsx
Speaking indicator in participants list of widget
https://mattermost.atlassian.net/browse/MM-42735
=> MM-42735 : Add indicator for speaking people in participants list in widget 

webapp/src/index.tsx
Not exactly sure what's going on since command is working fine locally but can't get it to work on Community. I believe it's due to the quotes.
=> Fix `/call stats` payload

webapp/src/rtcpeer/index.ts
While testing for various client error cases locally I couldn't get Chrome to drop the call in case of a sudden disconnection (Firefox is working as expected). Apparently `iceconnectionstatechange` is not firing with the `failed` state but `connectionstatechange` is so adding an handler for that as well.
=> Catch connection failed

webapp/src/components/expanded_view/component.tsx, webapp/src/shortcuts.ts
I tried to be a little too clever. Now handling push-to-talk as a separate action.
https://mattermost.atlassian.net/browse/MM-46905
=> [MM-46905] Fix mute/unmute shortcut in expanded view

webapp/src/action_types.ts, webapp/src/index.tsx, webapp/src/reducers.ts, webapp/src/types/types.ts
initial setup for redux, don't expect it to work right away as it is not tested, but should provide the places to modify if needed without breaking each others work.
=> initial redux setup

webapp/src/client.ts
We need to stringify the data before sending it to the server.
=> Fix send event 

webapp/src/components/expanded_view/component.tsx
=> Close on click outside

webapp/src/action_types.ts, webapp/src/index.tsx, webapp/src/reducers.ts, webapp/src/types/types.ts
Add a reaction timeout so that the emojis don't stay forever on top of the avatars. This applies to the notification stream as well, but I have not been able to test it properly.
--
=> Add a timeout for reactions

Makefile, webapp/src/components/call_widget/component.scss, webapp/src/components/call_widget/component.tsx, webapp/src/components/expanded_view/component.tsx, webapp/src/components/screen_source_modal/component.tsx, webapp/src/index.tsx, webapp/src/utils.ts, widget/src/index.tsx, widget/webpack.config.js
PR implements the logic to communicate with the Desktop side. This includes any necessary dynamic resizing of the widget.
https://mattermost.atlassian.net/browse/MM-46993
https://github.com/mattermost/desktop/pull/2265
=> [MM-46993] Global widget desktop communication

Makefile
Addresses #203 
https://mattermost.atlassian.net/browse/MM-47159
=> [MM-47159] Add linux-arm64 target to release build

webapp/src/index.tsx
Adding a check to avoid making unnecessary API calls and 401 errors getting thrown in the console.
https://mattermost.atlassian.net/browse/MM-47395
=> [MM-47395] Avoid fetching resources if user is not logged in

webapp/src/components/expanded_view/component.tsx
Mapping was undefined since we decoupled mute/unmute and push to talk actions.
https://mattermost.atlassian.net/browse/MM-47827
=> [MM-47827] Fix mute toggle shortcut tooltip in expanded view

webapp/src/client.ts, webapp/src/components/call_widget/component.tsx
Minimal change on this side, just improving visibility on streams and tracks for debugging purposes.
https://github.com/mattermost/rtcd/pull/77
https://mattermost.atlassian.net/browse/MM-47933
=> [MM-47933] Improve logging and tracking of resources

server/channel_state.go, server/session.go, server/utils.go, server/websocket.go
Just a little addition to help us figure out how much time is spent screen sharing while in calls.
=> Track total screen sharing duration per call

webapp/src/components/call_widget/component.tsx
- Fixes the move widget issue
- (I think the import changes in the PR were automatic)
- https://mattermost.atlassian.net/browse/MM-48435
=> MM-48435 - Desktop: Widget 'move' crosshairs moves the whole desktop app

Makefile, standalone/package-lock.json, standalone/skip_integrity_check.js
Just fixing the integrity failing on MacOS when building the standalone app.
=> Fix integrity checks

plugin.json, server/configuration.go, webapp/src/components/expanded_view/component.tsx, webapp/src/components/expanded_view/index.ts, webapp/src/components/expanded_view/recording_info_prompt.tsx, webapp/src/selectors.ts, webapp/src/types/types.ts
PR implements an info prompt that's showed to the host when the current call recording duration is approaching (10 minutes threshold) the configured limit.
https://mattermost.atlassian.net/browse/MM-48898
=> [MM-48898] Implement info prompt for approaching max call duration

webapp/src/components/expanded_view/component.tsx
- Fix reaction stream rendering while screensharing
- https://mattermost.atlassian.net/browse/MM-48719
=> MM-48719 - Fix reaction stream rendering while screensharing

README.md
Updating the README to be a little more informative and with links to the official documentation.
https://mattermost.atlassian.net/browse/MM-48853
=> [MM-48853] Update README

server/configuration.go
- https://mattermost.atlassian.net/browse/MM-49020
=> MM-49020 - Fix nil deref

e2e/tests/popout.spec.ts, webapp/src/components/call_widget/component.tsx, webapp/src/components/expanded_view/component.tsx
- Can you double check this doesn't break anything? I've tested it and it works. But I'm a little worried it was so easy -- is there a reason it wasn't included in the first place? 
- https://mattermost.atlassian.net/browse/MM-48657
=> MM-48657 - Add close button to pop-out window on desktop

webapp/src/websocket_handlers.ts
Merging desktop global widget PR reverted https://mattermost.atlassian.net/browse/MM-47006. Bringing that back.
I guess this highlights how important it is to run larger calls :)
https://mattermost.atlassian.net/browse/MM-49078
=> [MM-49078] Disable joining sound after threshold

webapp/src/components/expanded_view/component.tsx, webapp/src/components/expanded_view/reaction_button.tsx
- Hopefully fixed the linux problem
- Fixed a weird crashing bug for the emoji picker. Still not sure what's going on there.
- Removed the clicking-everywhere-drags issue I was seeing on 5.3
- Added a drag area to the top bar so that the global window can be moved. Decided to not add a cursor crosshairs, because I couldn't get the cursor to consistently show them in the entire area (they would disappear near the top of the window). Not sure why. This is good enough for now and we can revisit if design wants them added in the future.
- I've tested it on 5.3, 5.2, and webapp, but if you can please do the same for linux.
- https://mattermost.atlassian.net/browse/MM-49076
- https://mattermost.atlassian.net/browse/MM-49085
=> MM-48076 MM-49085: Global expanded view fixes

server/job_service.go
PR adds some logic to:
- Login to the job service on plugin activation. This makes sure that everything is configured correctly past the initial registration.
- Attempt to re-register if the first login attempt fails. This is particularly important to prevent getting locked out and requiring resetting some state in the k/v store.
https://mattermost.atlassian.net/browse/MM-49086
=> [MM-49086] Implement authentication check and re-registration logic in case of failure

e2e/global-setup.ts
Trying to fix some more failures that are coming our way.
=> Disable drafts tutorial when running e2e tests

README.md
=> Add supported tooling versions to build

webapp/src/client.ts
Forgot to remove a few things in #285
=> Remove references to voiceDetector

go.mod, go.sum, server/main.go, server/rtcd.go, webapp/src/index.tsx
Adding some jitter on (re)connection in an attempt to avoid bringing `rtcd` instance to a halt.
https://mattermost.atlassian.net/browse/MM-49998
=> [MM-49998] Add jitter on reconnections to rtcd

server/log.go, server/rtcd.go, server/websocket.go
PR slightly refactors the `rtcd` client connection logic aimed at limiting the number of authentication requests (either due to registrations or connections) and at the same type simplifying the logic where possible.
Also reviewed a few log statements and _downgraded_ some errors.
https://mattermost.atlassian.net/browse/MM-49766
=> [MM-49766] Review rtcd connection logic

server/plugin.go
Fixes #314 
https://mattermost.atlassian.net/browse/MM-50234
=> [MM-50234] Respect privacy settings when using name

webapp/src/components/call_widget/component.tsx
PR adds support for zooming. Touching desktop code I realized the overly complex nature of the resizing logic and decided to improve it. 
Now we are simply passing a rectangular size (width + height) from widget to desktop which gets automatically scaled accordingly based on the current zoom factor. 
This simplification should also unblock further work on the widget since we'd just need to update `getGlobalWidgetBounds` here in order to get everything working on the desktop side.
https://user-images.githubusercontent.com/1832946/217059286-9f432b65-4e43-44a5-8ded-1b9668ba3eae.mov
https://mattermost.atlassian.net/browse/MM-48658
https://github.com/mattermost/desktop/pull/2545
=> [MM-48658] Improve global widget resizing

go.mod, go.sum, plugin.json
Bumping recording service dependency and recorder image versions.
=> Bump recording services

.editorconfig, standalone/.eslintrc.json, standalone/package-lock.json, standalone/package.json, standalone/skip_integrity_check.js, standalone/webpack.config.js, webapp/.eslintrc.json, webapp/package-lock.json, webapp/package.json, webapp/skip_integrity_check.js, webapp/src/components/call_error_modal.tsx, webapp/src/components/call_widget/component.tsx, webapp/src/index.tsx, webapp/src/slash_commands.tsx, webapp/src/utils.ts, webapp/webpack.config.js
- Adds eslint rules for unused imports and vars, just like Go
- Someday you'll be a grown up language too, JS. Keep trying.
- https://mattermost.atlassian.net/browse/MM-51497
=> MM-51497 - Add eslint rules for unused imports, vars

e2e/tests/join_call.spec.ts, webapp/src/action_types.ts, webapp/src/components/call_widget/component.scss, webapp/src/components/call_widget/component.tsx, webapp/src/components/call_widget/index.ts, webapp/src/constants.ts, webapp/src/reducers.ts, webapp/src/selectors.ts, webapp/src/websocket_handlers.ts
PR reworks the (now broken) abysmal logic to show the notification pill for recently joined participants. 
Still the CSS animation could use some improvements but that's a bit more tricky and will need some figuring out.
=> Improve joined users widget notification

.github/workflows/cd.yml
- Fix broken rudder keys
- https://mattermost.atlassian.net/browse/MM-51985
=> MM-51985 - Fix for: Rudder keys are missing from prod builds

standalone/src/recording/components/recording_view/index.tsx
PR fixes a couple of rendering issues:
1. Screen sharing player could overflow and hide the footer if the content was particularly stretched.
2. Reaction stream was not position properly.
https://mattermost.atlassian.net/browse/MM-52117
=> [MM-52117] Fix rendering issues in recording view

server/telemetry.go, webapp/src/slash_commands.tsx, webapp/src/types/telemetry.ts
I forgot to update the server counterpart so the events were being sent but ignored by the server. Also added coverage to the related slash commands.
https://mattermost.atlassian.net/browse/MM-52290
=> [MM-52290] Fix recording telemetry events

webapp/package-lock.json, webapp/package.json, webapp/src/actions.ts, webapp/src/index.tsx, webapp/src/types/types.ts
`axios` --> :wastebasket: 
https://github.com/mattermost/calls-common/pull/7
https://mattermost.atlassian.net/browse/MM-44707
=> [MM-44707] Replace `axios` calls with our own HTTP client

standalone/src/init.ts
We need to pass the config flag on the standalone side as well in order for simulcast to be available on Desktop.
=> Enable simulcast support on desktop

plugin.json
Bumping calls recorder image version to latest.
=> Bump recorder version

e2e/tests/popout.spec.ts, webapp/src/components/expanded_view/component.tsx, webapp/src/components/expanded_view/reaction_button.tsx
Unfortunately this instance was missed completely in https://github.com/mattermost/mattermost-plugin-calls/pull/418 . A bit surprised this wasn't reported sooner but here we are. May be worth considering a dot release.
https://mattermost.atlassian.net/browse/MM-52928
=> [MM-52928] Fix raising hand button state in expanded view

standalone/package-lock.json, standalone/package.json, webapp/package-lock.json, webapp/package.json
Updating to fix the screen sharing issue. 
Will create a custom build from this branch to test on Community next week.
https://mattermost.atlassian.net/browse/MM-53069
=> [MM-53069] Update calls-common

plugin.json, server/configuration.go
- Add a Beta system console setting for Calls ringing, because the feature should be considered Beta (or even experimental) until probably 8.1 (which is when it should be released for Mobile as well).
- Default off, until later.
- https://mattermost.atlassian.net/browse/MM-53274
=> MM-53274 - Add a Beta system console setting for Calls ringing

server/activate.go, server/job_service.go
Now that we made the service operate almost statelessly to work well with Kubernetes, we need to account for the fact that subsequent HTTPs requests may hit different instances and fail due to missing authentication. The simplest way to deal with this problem is to implement a basic re-try mechanism.
I am not in love with this approach but the cleaner alternative is to either rethink the whole authentication logic (e.g. using a pre-shared secret) or implement some sort of shared auth service (e.g. using an external database). Neither of these are of simple/quick execution so opting for the dirtier fix.
https://mattermost.atlassian.net/browse/MM-53804
=> [MM-53804] Add simple re-try logic to job creation

standalone/src/init.ts, standalone/src/recording/index.tsx
We had a recording job failing during initialization (see ticket). Adding a couple of extra catch blocks to try and get better output. 
https://mattermost.atlassian.net/browse/MM-53951
=> [MM-53951] Catch some potentially unhandled errors

server/session.go
As an addendum to https://github.com/mattermost/mattermost-plugin-calls/pull/498, we also bump the size of the queue of ws messages or we could hit some issues.
https://mattermost.atlassian.net/browse/MM-54216
=> [MM-54216] Bump msgChSize

server/api.go, server/utils.go, server/utils_test.go
- Fixed the crash. Learning: never assume anything from browsers.
Fixes https://github.com/mattermost/mattermost-plugin-calls/issues/504
- https://mattermost.atlassian.net/browse/MM-54259
=> MM-54259 - Fix: Panic in isMobilePostGA

server/api.go, server/store.go
- Cherry picked from https://github.com/mattermost/mattermost-plugin-calls/pull/508
- https://mattermost.atlassian.net/browse/MM-54313
=> MM-54313 - Fix: panic in handleGetAllChannels

webapp/src/index.tsx
- We needed a link handler.
- Doesn't fix desktop, bc of https://mattermost.atlassian.net/browse/MM-51522
- https://mattermost.atlassian.net/browse/MM-54224
=> MM-54224 - Fix: Clicking a link to a thread from the popup does nothing

server/api.go, server/utils.go, server/utils_test.go
- Cherry picks #505 and #511 to  release-0.13 branch for a v0.13.1 dot release, to be prepackaged to the 7.8 ESR release.
- https://mattermost.atlassian.net/browse/MM-54361
=> MM-54361 - Two cherry picks - #505 and #511

.github/workflows/ci.yml
- Let's see if https://github.com/mattermost/actions-workflows/pull/35 lets us fix the builds
- none
=> Set golang-version for the build process

server/channel_state.go, server/plugin.go, server/utils.go
- Cherry picks of #530 and #532 for v0.19.2
- none
=> Cherry picks for 0.19.2

server/performance/metrics.go, server/websocket.go
Porting the fix in https://github.com/mattermost/mattermost-plugin-calls/pull/523 to the main branch as well. The rtcd update will happen naturally at a later time when we release v0.12.0 so not including that yet.
https://mattermost.atlassian.net/browse/MM-54445
=> [MM-54445] Review metrics

e2e/tests/join_call.spec.ts, e2e/utils.ts, webapp/src/reducers.ts
Porting the fix in https://github.com/mattermost/mattermost-plugin-calls/pull/524 to `main`.
https://mattermost.atlassian.net/browse/MM-54494
=> [MM-54494] Keep backwards compatibility with older MM versions

webapp/src/components/call_widget/component.tsx, webapp/src/components/expanded_view/component.tsx
Porting the change we made on the mobile side.
=> Show (you) suffix only for current session

plugin.json
=> Bump recorder version to latest

plugin.json, server/configuration.go, server/job_service.go, webapp/src/action_types.ts, webapp/src/actions.ts, webapp/src/components/admin_console_settings/recordings/enable_transcriptions.tsx, webapp/src/components/admin_console_settings/recordings/transcriber_model_size.tsx, webapp/src/index.tsx, webapp/src/reducers.ts
This is an important setting as it directly affects quality and performance of the whole process. It will also be useful to run the upcoming performance tests.
=> [MM-53432] Model size config setting

e2e/tests/start_call.spec.ts, e2e/utils.ts, webapp/src/browser_routing.ts, webapp/src/components/call_widget/component.tsx, webapp/src/components/incoming_calls/hooks.ts
Looks like we already had the proper util function to do it. Just making sure that works in case we are calling from the popout.
https://mattermost.atlassian.net/browse/MM-56051
=> [MM-56051] Fix clicking widget channel link

go.mod, go.sum, plugin.json
Bumping the main dependencies to the latest versions.
=> Bump main dependencies

go.mod, go.sum, plugin.json
- Update calls-transcriber to v0.1.5
- none
=> Update calls-transcriber to v0.1.5

standalone/package-lock.json, standalone/package.json, webapp/package-lock.json, webapp/package.json
Bumping `calls-common` to include the recent changes to `RTCPeer` (https://github.com/mattermost/calls-common/pull/22).
=> Bump calls-common

e2e/tests/start_call.spec.ts, server/plugin.go
PR prevents the call post from being modified as it could cause issues like messing with metadata such as recording file ids.
More context in the original comment https://github.com/mattermost/mattermost-plugin-calls/pull/549#discussion_r1380437276
https://mattermost.atlassian.net/browse/MM-55264
=> [MM-55264] Prevent call post from being modified

plugin.json
=> Bump recorder image

server/telemetry.go
- I missed adding these to the server side, thanks for the heads up.
- https://mattermost.atlassian.net/browse/MM-56257
=> MM-56257 - Add missing telemetry events to server-side checks

go.mod, go.sum, plugin.json
=> Bump calls-recorder to latest

e2e/page.ts, e2e/tests/host_controls.spec.ts, webapp/src/components/badge.tsx, webapp/src/components/call_widget/component.tsx
- e2e tests for `/call host username`
- https://mattermost.atlassian.net/browse/MM-57529
=> [MM-57529] e2e tests for host change slash command

plugin.json
Bumping recorder and transcriber to latest dot releases.
=> Bump images

standalone/package-lock.json, standalone/package.json, webapp/package-lock.json, webapp/package.json
- Bump dep for calls-common since I just merged it and previous branch is now gone
- https://mattermost.atlassian.net/browse/MM-57777
=> [MM-57777] Bump calls-common dep

.github/workflows/ci.yml, .golangci.yml, go.mod, lt/client/client.go, lt/client/tts.go, lt/cmd/speech/main.go, lt/cmd/speech/script.go, server/bot_api.go, server/cloud_limits.go, server/db/migrate.go, server/host_controls.go, server/log.go, server/main.go, server/plugin_test.go, server/public/job.go, server/push_notifications.go, server/rtcd.go, server/state_test.go, server/testutils/containers.go, server/utils.go, server/websocket.go
Same as https://github.com/mattermost/rtcd/pull/133, porting on this side for consistency.
=> [MM-57571] Improve linting

webapp/src/components/admin_console_settings/recordings/live_captions_language.tsx, webapp/src/components/admin_console_settings/recordings/live_captions_model_size.tsx, webapp/src/components/admin_console_settings/recordings/live_captions_num_threads_per_transcriber.tsx, webapp/src/components/admin_console_settings/recordings/live_captions_num_transcribers.tsx, webapp/src/components/admin_console_settings/recordings/transcriber_model_size.tsx, webapp/src/components/admin_console_settings/recordings/transcriber_num_threads.tsx
- This is a short-term fix until we do the full redesign, but at least now things are visible only if their prerequisites are enabled. Before, some were and some weren't; it was a bit incorrect (noticed when I was doing the docs).
- https://mattermost.atlassian.net/browse/MM-58006
=> [MM-58006] System console live captions and transcriber settings visibility

standalone/package-lock.json, standalone/package.json, standalone/src/init.ts, webapp/package-lock.json, webapp/package.json, webapp/src/websocket_handlers.ts
- Update calls-common, refactor to use new host control ws msg definitions
- https://mattermost.atlassian.net/browse/MM-57919
=> [MM-57919] Use new host controls ws msgs

webapp/src/components/host_notices.tsx
- Fix bg and color on dark themes
| old | new |
|--|--|
| <img width="400" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/05a189fe-6f3c-4a90-a23e-3a14cba719c1"> | <img width="401" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/6a9c2f33-b382-4310-95b2-4b45a709dd54"> |
| <img width="426" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/c60603bc-31db-40a1-84d8-ca13b3a9ed35"> | <img width="327" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/ec443a4a-b273-464a-9e58-292e928bfaa9"> |
- https://mattermost.atlassian.net/browse/MM-58232
=> [MM-58232] Host notices: fix background and color

e2e/tests/join_call.spec.ts
Fix: https://github.com/mattermost/mattermost/pull/26420#issuecomment-2113202367
=> chore(cypress): Fix user profile e2e test

webapp/src/components/expanded_view/component.tsx
Fixing a couple of outstanding issues that were reported today.
https://mattermost.atlassian.net/browse/MM-58265
https://mattermost.atlassian.net/browse/MM-58266
=> [MM-58265] Fix outstanding CSS issues in pop out view

webapp/i18n/en.json, webapp/src/components/custom_post_types/post_type_transcription.tsx
UX Feedback to remove question mark.
=> Remove question mark from meeting summary button.

.config/notice-file/config.yaml, .gitignore, NOTICE.txt
Introduce new packages on NOTICE.txt file 
Related PR: https://github.com/mattermost/delivery-platform/pull/121 
https://mattermost.atlassian.net/browse/CLD-6877
=> feat: Introduce new notice-file-generation

server/websocket.go
Ceiling tests have revealed a race condition while leaving a call before `handleJoin` has finished that could lead to indefinitely stuck sessions. 
A proper fix would be quite challenging so I am opting for a "good enough" workaround. If upon WebSocket disconnects we don't find the session we try again after a few seconds, giving enough time to any potentially concurrent `handleJoin` execution to complete.
https://mattermost.atlassian.net/browse/MM-58325
=> [MM-58325] Handle stuck session edge case

server/session.go
When implementing the cleanup code in https://github.com/mattermost/mattermost-plugin-calls/pull/704, I failed to realize that this path would only be running on a single HA node, whichever has the lock when removing the last session from the global state.
This caused some of the batchers in other nodes to be leaked. By itself, this wasn't a huge deal until they would be re-used the next time around for a call in the same channel. That would cause a much nastier bug since the [session count](https://github.com/mattermost/mattermost-plugin-calls/blob/b501c6be2becca2fcc7a4403938da8380314dcd1/server/session.go#L536) of the previous call would determine the queue length so any larger call would have had a high chance of causing channel full errors and batched actions to be dropped, leading to …
=> Fix leaking batchers in HA environment

webapp/src/components/admin_console_settings/common.tsx, webapp/src/components/admin_console_settings/recordings/enable_recordings.tsx, webapp/src/components/admin_console_settings/rtcd_service_url/index.tsx
- Noticed this while working with Abhijit about the system console issues
| before | after |
|--|--|
| <img width="948" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/91811f33-282b-4f1c-9844-655823fafb08"> | <img width="939" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/7275e285-cd6f-4cb9-8d1d-59688e542778"> |
| <img width="919" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/684aed73-160e-48e7-8401-aafaad66a493"> | <img width="938" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/a424d21c-8f51-43ed-8be0-34b4e92023e5"> |
- https://mattermost.atlassian.net/browse/MM-58364
=> [MM-58364] System console cleanup

server/websocket.go, server/websocket_test.go
Fixing a small regression introduced in https://github.com/mattermost/mattermost-plugin-calls/pull/609 that caused sending duplicate events to the bot, causing the double reaction issue.
This was unexpected primarily because of the interesting precedence rules in WebSocket broadcasts:
https://github.com/mattermost/mattermost/blob/04181247f8a42fe8313a28df864224cd2e4850e8/server/channels/app/platform/web_conn.go#L867-L877 
https://mattermost.atlassian.net/browse/MM-58494
=> [MM-58494] Fix duplicate ws event to bot

README.md
We forgot to update the README.
=> Update node/npm version requirements

e2e/tests/notifications.spec.ts, webapp/src/actions.ts, webapp/src/reducers.ts, webapp/src/websocket_handlers.ts
- cherry pick #784 and #792 
- none
=> Cherry picks for 0.28.2

.github/workflows/e2e.yml, e2e/scripts/prepare-server.sh, server/db/stats_store_test.go
Working with dates is a bit tricky. Test could fail based on which day of the month we were on.
=> Fix flaky test

.github/workflows/e2e.yml, e2e/config-patch.json, e2e/overlay-config.jq, e2e/scripts/run.sh
Fixing the pipeline after some subtle breaking changes on the server (see https://github.com/mattermost/mattermost/pull/27986#discussion_r1762107270). Implementing a workaround while we wait for a proper solution to land upstream.
https://mattermost.atlassian.net/browse/MM-60557
=> [MM-60557] Fix e2e tests pipeline

.github/workflows/e2e.yml, go.mod, go.sum, lt/go.mod, lt/go.sum, plugin.json
Final touches before releasing.
=> [MM-60209] Prepare v1.1 release

.github/workflows/e2e.yml, e2e/docker/docker-compose.yaml, e2e/docker/postgres.conf, e2e/scripts/prepare-server.sh, webapp/i18n/en.json, webapp/src/components/custom_post_types/post_type/component.tsx, webapp/src/utils.test.ts, webapp/src/utils.ts
Cherry-pick of 74d6f31 in `release-1.2` to prepare for dot release.
https://mattermost.atlassian.net/browse/MM-61166
=> [MM-61166] Cherrypick to `release-1.2`

e2e/package-lock.json, e2e/package.json, e2e/playwright.config.ts, e2e/tests/desktop.spec.ts, e2e/tests/popout.spec.ts, webapp/src/components/expanded_view/component.tsx, webapp/src/components/incoming_calls/call_incoming_condensed.tsx, webapp/src/components/screen_source_modal/component.tsx
Cherry-picking some fixes for v0.29.4
- b5a42112f79ccdfa5bbdd439da85c9d26ab9ce34
- ac3076947a819086e84246054eb1ab4f28d53960
- e906dd2c826b40a670694e974662dbc16aaf8f1b
=> Prepare v0.29.4

.github/workflows/e2e.yml, go.mod, go.sum, lt/go.mod, lt/go.sum, plugin.json
=> Prepare v1.3.0

server/activate.go
Cherry-picking the fix in https://github.com/mattermost/mattermost-plugin-calls/pull/912 to prepare a v0.29.6 dot release.
=> Cherrypick MM-62064 v0.29

e2e/tests/media.spec.ts
The AV1 e2e tests have been failing too often for my liking, so we are trying something slightly different and hopefully more consistent.
=> Fix flaky AV1 e2e

.github/workflows/generate-e2e-report.yml
Fix the E2E testing report workflow, reducing the token scope to the minimum required.
https://mattermost.atlassian.net/browse/MM-62376
=> Fix E2E reporting workflow

standalone/package-lock.json, webapp/package-lock.json
Updating `nanoid` dependency to v3.3.8
https://mattermost.atlassian.net/browse/MM-62886
=> [MM-62886] Update `nanoid` package to v3.3.8

.github/workflows/e2e.yml, go.mod, go.sum, lt/go.mod, lt/go.sum, plugin.json
Bumping rtcd and calls-recorder to latest before we release.
=> Prepare release 1.7

webapp/src/components/custom_post_types/post_type/component.tsx
*Before*
*After*
https://mattermost.atlassian.net/browse/MM-63869
=> [MM-63869] Fix overflow in call thread

go.mod, go.sum, server/activate.go
Updating after we merged https://github.com/mattermost/rtcd/pull/176
=> Update RTCD to latest

Makefile
https://github.com/mattermost/mattermost-plugin-starter-template/pull/218
=> Adding mattermost-plugin-starter-template/pull/218 to the calls plugin

.github/workflows/ci.yml
update ci pipeline with latest tag
https://mattermost.atlassian.net/browse/CLD-9264
=> update ci pipeline with latest tag

go.mod, go.sum, lt/go.mod, lt/go.sum
=> Update rtcd 1.2.0

server/bot_api.go, server/bot_api_test.go
Adding stricter checks and some test coverage.
=> Improve `handleBotUploadData`

.github/workflows/e2e.yml, plugin.json
- https://mattermost.atlassian.net/browse/MM-64612
=> [MM-64612] Calls v1.10.0 release - new recorder/transcriber images

lt/go.mod, lt/go.sum
https://github.com/mattermost/rtcd/pull/183
=> Allow TCP candidates in lt client
